-- Migration: RAG Chunks — Drenagem (rod:dren:*)
-- Date: 2026-08-04 (Schema real: manta_rag_documents + manta_rag_chunks)
-- Status: Fase II consolidation
-- Source: .claude/knowledge/rodovias/drenagem/10-drenagem-especializacoes.md
-- Chunks: 15 entries covering 15 specializations

BEGIN TRANSACTION;

-- 1. Create document record
INSERT INTO manta_rag_documents (doc_id, uri, titulo, tipo, projeto, data_indexacao, hash_conteudo, metadados, fonte_origem)
VALUES (
  'rod-dren-especializacoes-20260804',
  'knowledge/rodovias/drenagem/10-drenagem-especializacoes.md',
  'Drenagem — 15 Especializações (hidrologia, superficial, subsuperficial, integrado, O&M)',
  'knowledge_base',
  'rodovias',
  NOW(),
  'workflow-consolidacao-15agentes-920k-tokens',
  jsonb_build_object(
    'collection_slug', 'rodovias-drenagem',
    'prefix_storage', 'rod:dren:',
    'source_type', 'workflow-consolidacao',
    'agents_count', 15,
    'total_tokens_consolidated', 920000,
    'agent_specializations', jsonb_build_array('hidrologia', 'metodo_racional', 'metodo_scs', 'tempo_concentracao', 'sarjetas', 'bueiros', 'tubulacoes', 'dissipadores', 'drenagem_profunda', 'filtros_geotextil', 'compactacao_drenagem', 'projeto_integrado', 'manutencao_diagnostico', 'problemas_solucoes', 'qualidade_agua')
  ),
  'workflow-consolidacao-60agentes'
)
ON CONFLICT (doc_id) DO NOTHING;

-- 2. Insert chunks from 15 specializations
INSERT INTO manta_rag_chunks (doc_id, posicao, texto, tokens, metadados_chunk)
SELECT
  'rod-dren-especializacoes-20260804',
  row_number() OVER (ORDER BY posicao),
  texto,
  tokens,
  metadados_chunk
FROM (
  SELECT 1 as posicao,
    'Fundamentos hidrológicos — ciclo água (evaporação, precipitação, escoamento), bacias hidrográficas, coeficiente escoamento C. C varia: asfalto 0.80-0.95, grama 0.20-0.30, floresta 0.10-0.20. Tempo concentração tc (tempo chuva atingir ponto jusante): fórmulas Kirpich, SCS, correlação regional. Precipitação de projeto: tempo retorno 10-25 anos típico (rodovias), altura máxima consultada isoieta (mapas DNIT/ANA). Exemplo: bacia 15 ha, C=0.6, tc=20 min, i=100 mm/h → Q=2.73 m³/s (método racional). Impacto: projeto drenagem depende precipitação, erros subestimam riscos (alagamento, erosão). Monitoramento: pluviômetro estação base, série histórica 10+ anos.' as texto,
    CEIL(LENGTH('Fundamentos hidrológicos — ciclo água (evaporação, precipitação, escoamento), bacias hidrográficas, coeficiente escoamento C. C varia: asfalto 0.80-0.95, grama 0.20-0.30, floresta 0.10-0.20. Tempo concentração tc (tempo chuva atingir ponto jusante): fórmulas Kirpich, SCS, correlação regional. Precipitação de projeto: tempo retorno 10-25 anos típico (rodovias), altura máxima consultada isoieta (mapas DNIT/ANA). Exemplo: bacia 15 ha, C=0.6, tc=20 min, i=100 mm/h → Q=2.73 m³/s (método racional). Impacto: projeto drenagem depende precipitação, erros subestimam riscos (alagamento, erosão). Monitoramento: pluviômetro estação base, série histórica 10+ anos.') / 4)::int as tokens,
    jsonb_build_object('prefix_storage', 'rod:dren:hidrologia', 'categoria', 'hidrologia', 'section', '1', 'subsection', '1.1', 'collection_slug', 'rodovias-drenagem') as metadados_chunk
  UNION ALL SELECT 2, 'Método Racional — Q = C × I × A / 360 (SI: Q m³/s, C adimensional, I mm/h, A ha). Aplicação: bacias pequenas <50 ha (hipótese: chuva uniforme, resposta linear). Parâmetros: C (tipo uso solo), I (curva IDF local, duração=tc), A (levantamento topográfico/SIG). Curva IDF (intensidade-duração-frequência): consultada publicações ANA/DNIT região. Exemplo: bacia drenagem em rodovia 8 ha, C=0.7 (asfalto+grama), tc=15 min, tempo retorno 10 anos I=80mm/h → Q = 0.7×80×8/360 = 1.56 m³/s. Norma DNIT IPR 382/2020. Limitação: não considera armazenamento bacia (subestima em bacias grandes).', CEIL(LENGTH('Método Racional — Q = C × I × A / 360 (SI: Q m³/s, C adimensional, I mm/h, A ha). Aplicação: bacias pequenas <50 ha (hipótese: chuva uniforme, resposta linear). Parâmetros: C (tipo uso solo), I (curva IDF local, duração=tc), A (levantamento topográfico/SIG). Curva IDF (intensidade-duração-frequência): consultada publicações ANA/DNIT região. Exemplo: bacia drenagem em rodovia 8 ha, C=0.7 (asfalto+grama), tc=15 min, tempo retorno 10 anos I=80mm/h → Q = 0.7×80×8/360 = 1.56 m³/s. Norma DNIT IPR 382/2020. Limitação: não considera armazenamento bacia (subestima em bacias grandes).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:metodo_racional', 'categoria', 'metodo_racional', 'section', '1', 'subsection', '1.2', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 3, 'Método SCS (Soil Conservation Service) — para bacias 50-2500 ha. Entrada: precipitação total (P), número escoamento CN (tipo solo + uso solo + condição hidrológica). Cálculo: retenção potencial S = (25400/CN) - 254, escoamento Pe = (P-0.2S)² / (P+0.8S), volume Q=Pe×A. CN table: 25-98 conforme solo (arenoso 40-60, argiloso 70-90) e uso (pavimento 95-98, floresta 25-45). Vantagem: mais detalhado que método racional, conta armazenamento. Desvantagem: sensível estimativa CN. Software: HEC-HMS USACE, planilha Excel DNIT. Exemplo: bacia 200 ha, CN=70 (solo argiloso, cobertura mista), P=120mm → S=109mm, Pe=62mm, volume=1240m³ (Q médio ~0.15 m³/s).', CEIL(LENGTH('Método SCS (Soil Conservation Service) — para bacias 50-2500 ha. Entrada: precipitação total (P), número escoamento CN (tipo solo + uso solo + condição hidrológica). Cálculo: retenção potencial S = (25400/CN) - 254, escoamento Pe = (P-0.2S)² / (P+0.8S), volume Q=Pe×A. CN table: 25-98 conforme solo (arenoso 40-60, argiloso 70-90) e uso (pavimento 95-98, floresta 25-45). Vantagem: mais detalhado que método racional, conta armazenamento. Desvantagem: sensível estimativa CN. Software: HEC-HMS USACE, planilha Excel DNIT. Exemplo: bacia 200 ha, CN=70 (solo argiloso, cobertura mista), P=120mm → S=109mm, Pe=62mm, volume=1240m³ (Q médio ~0.15 m³/s).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:metodo_scs', 'categoria', 'metodo_scs', 'section', '1', 'subsection', '1.3', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 4, 'Tempo de concentração tc — tempo chuva atingir exutório bacia. Fórmula Kirpich: tc (min) = 0.0195 × (L/√S)^0.77 (L comprimento bacia m, S declividade adimensional). Fórmula SCS: tc (h) = (L/3600/v)^0.6 (v velocidade escoamento m/s, estimada terreno). Valores típicos: terreno plano arenoso tc 30-60 min, montanhoso rochoso tc 5-15 min. Impacto: tc reduzido → I (intensidade) maior → Q maior. Erros comuns: superestimar L (toda bacia vs apenas fluxo principal), usar declividade média (usar mínima). Aplicação rodovia: drenar pontos altos (cristas, ombros) para jusante (despejo sarjeta/boca-leão). Monitoramento: visualizar fluxo em chuva, ajustar tc se observações indicarem discrepância.', CEIL(LENGTH('Tempo de concentração tc — tempo chuva atingir exutório bacia. Fórmula Kirpich: tc (min) = 0.0195 × (L/√S)^0.77 (L comprimento bacia m, S declividade adimensional). Fórmula SCS: tc (h) = (L/3600/v)^0.6 (v velocidade escoamento m/s, estimada terreno). Valores típicos: terreno plano arenoso tc 30-60 min, montanhoso rochoso tc 5-15 min. Impacto: tc reduzido → I (intensidade) maior → Q maior. Erros comuns: superestimar L (toda bacia vs apenas fluxo principal), usar declividade média (usar mínima). Aplicação rodovia: drenar pontos altos (cristas, ombros) para jusante (despejo sarjeta/boca-leão). Monitoramento: visualizar fluxo em chuva, ajustar tc se observações indicarem discrepância.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:tempo_concentracao', 'categoria', 'tempo_concentracao', 'section', '1', 'subsection', '1.4', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 5, 'Sarjetas (canaletas laterais) — transporte fluxo superficial pavimento. Dimensionamento Manning: Q = (1/n)×A×R^(2/3)×√i. n (coeficiente Manning 0.012-0.020 hormigão liso), A (área molhada), R (raio hidráulico), i (declividade). Exemplo: sarjeta triangular 0.5m base, 0.15m profundidade, n=0.015, i=0.02 (2%) → Q=0.8 m³/s (capacidade). Velocidade mínima 0.5 m/s (evitar sedimentação), máxima 3-4 m/s (erosão contenção). Proteção: gavião (rochas), concreto projetado, geotêxtil. Posicionamento: pé talude + ombro pavimento (dupla contenção). Limpeza: anual (sedimento, folhas), pós-chuva pesada (detritos). Custo: R$ 20-80/m² (varia tipo contenção). Norma DNIT IPR 382.', CEIL(LENGTH('Sarjetas (canaletas laterais) — transporte fluxo superficial pavimento. Dimensionamento Manning: Q = (1/n)×A×R^(2/3)×√i. n (coeficiente Manning 0.012-0.020 hormigão liso), A (área molhada), R (raio hidráulico), i (declividade). Exemplo: sarjeta triangular 0.5m base, 0.15m profundidade, n=0.015, i=0.02 (2%) → Q=0.8 m³/s (capacidade). Velocidade mínima 0.5 m/s (evitar sedimentação), máxima 3-4 m/s (erosão contenção). Proteção: gavião (rochas), concreto projetado, geotêxtil. Posicionamento: pé talude + ombro pavimento (dupla contenção). Limpeza: anual (sedimento, folhas), pós-chuva pesada (detritos). Custo: R$ 20-80/m² (varia tipo contenção). Norma DNIT IPR 382.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:sarjetas', 'categoria', 'sarjetas', 'section', '2', 'subsection', '2.1', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 6, 'Bueiros — tubulações transversais drenagem. Cálculo diâmetro: Q = V×A (V velocidade m/s, A seção tubo). Entrada: Q método racional/SCS, tipo solo (permeabilidade), profundidade assentamento. Diâmetro comercial: 400, 600, 800, 1000, 1200 mm (tubos concreto). Velocidade recomendada 0.6-3 m/s (erosão entrada/saída >3, sedimentação <0.6). Proteção entrada/saída: boca-leão (cone aço), dissipador (pedras), defensas. Posicionamento: perpendicular fluxo, profundidade ≥1m (carga cobertura), espaçamento típico 100-200m. Impacto: insuficiente provoca alagamento pista (risco segurança), adequado reduz dano erosão. Custo: R$ 5.000-15.000 bueiro (tubo+escavação+proteção). Limpeza: anual vácuo, verificação pós-chuva obstrução.', CEIL(LENGTH('Bueiros — tubulações transversais drenagem. Cálculo diâmetro: Q = V×A (V velocidade m/s, A seção tubo). Entrada: Q método racional/SCS, tipo solo (permeabilidade), profundidade assentamento. Diâmetro comercial: 400, 600, 800, 1000, 1200 mm (tubos concreto). Velocidade recomendada 0.6-3 m/s (erosão entrada/saída >3, sedimentação <0.6). Proteção entrada/saída: boca-leão (cone aço), dissipador (pedras), defensas. Posicionamento: perpendicular fluxo, profundidade ≥1m (carga cobertura), espaçamento típico 100-200m. Impacto: insuficiente provoca alagamento pista (risco segurança), adequado reduz dano erosão. Custo: R$ 5.000-15.000 bueiro (tubo+escavação+proteção). Limpeza: anual vácuo, verificação pós-chuva obstrução.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:bueiros', 'categoria', 'bueiros', 'section', '2', 'subsection', '2.2', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 7, 'Tubulações e materiais — concreto (TUCC simples), PEAD (polietileno alta densidade, flexível, leve), PVC (rígido, químico-resistente), aço corrugado (robustez, custo). Concreto: vida 50+ anos, resistência compressão 40 MPa típica, proteção interior revestimento epóxi (salinidade). PEAD: flexível, deformação suporta ±5% (lenimenta hiperestático), custo -30% concreto, risco esmagamento sobrecarga (evitar <1.5m cobertura). PVC: plástico rígido, resistente ácidos, custo intermediário, vida 30-40 anos. Aço: corrosão risco (revestimento epóxi/alquitrão), pesado (equipamento elevação), aplicação drenagem profunda/pressão. Seleção critério: vida projeto, custo total, condições químicas solo (agressividade), acesso manutenção.', CEIL(LENGTH('Tubulações e materiais — concreto (TUCC simples), PEAD (polietileno alta densidade, flexível, leve), PVC (rígido, químico-resistente), aço corrugado (robustez, custo). Concreto: vida 50+ anos, resistência compressão 40 MPa típica, proteção interior revestimento epóxi (salinidade). PEAD: flexível, deformação suporta ±5% (lenimenta hiperestático), custo -30% concreto, risco esmagamento sobrecarga (evitar <1.5m cobertura). PVC: plástico rígido, resistente ácidos, custo intermediário, vida 30-40 anos. Aço: corrosão risco (revestimento epóxi/alquitrão), pesado (equipamento elevação), aplicação drenagem profunda/pressão. Seleção critério: vida projeto, custo total, condições químicas solo (agressividade), acesso manutenção.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:tubulacoes', 'categoria', 'tubulacoes', 'section', '2', 'subsection', '2.3', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 8, 'Dissipadores energia — saída bueiro/sarjeta com energia cinética reduz erosão jusante. Tipos: (1) bacia amortecimento (escavação em roco, preenchimento pedra, dissipação impacto), (2) degraus (redução velocidade por etapas), (3) reversão fluxo (parede frontal, volta submersão). Projeto: repouso mínimo 0.5m (profundidade bacia) × 2m (comprimento), preenchimento brita 5-10cm (absorve energia). Exemplo: saída Q=2m³/s, V=4 m/s (erosão alta) → bacia 2×3m, pedra 10cm reduz V para <1.5 m/s (seguro jusante). Custo: R$ 2.000-5.000 dissipador (escavação + brita + geotêxtil). Manutenção: limpeza anual (colmatação sedimento), verificação estabilidade pedra (deslocamento chuva forte). Norma DNIT IPR 382.', CEIL(LENGTH('Dissipadores energia — saída bueiro/sarjeta com energia cinética reduz erosão jusante. Tipos: (1) bacia amortecimento (escavação em roco, preenchimento pedra, dissipação impacto), (2) degraus (redução velocidade por etapas), (3) reversão fluxo (parede frontal, volta submersão). Projeto: repouso mínimo 0.5m (profundidade bacia) × 2m (comprimento), preenchimento brita 5-10cm (absorve energia). Exemplo: saída Q=2m³/s, V=4 m/s (erosão alta) → bacia 2×3m, pedra 10cm reduz V para <1.5 m/s (seguro jusante). Custo: R$ 2.000-5.000 dissipador (escavação + brita + geotêxtil). Manutenção: limpeza anual (colmatação sedimento), verificação estabilidade pedra (deslocamento chuva forte). Norma DNIT IPR 382.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:dissipadores', 'categoria', 'dissipadores', 'section', '2', 'subsection', '2.4', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 9, 'Drenagem profunda — drenos longitudinais dentro aterro/base, capturam água freática. Composição: núcleo PEAD perfurado 100-150mm (captação), envoltório brita 5-10cm (filtro física), geotêxtil envolvente (retenção finos). Espaçamento: cada 20-50m (depende gradiente) ao longo rodovia. Posicionamento: linha máxima saturação esperada (levantamento piezômetro). Vazão: Q=k×A×i (k permeabilidade 10^-1 cm/s BGS, A seção dreno, i declividade 2-4%). Saída: boca-leão/dissipador pé talude ou bacia sedimentação (evita descarga brusca). Manutenção: limpeza cada 2-3 anos (risco obstrução silte), vácuo com bomba submersível. Custo: R$ 1.000-3.000/100m (tubo+brita+mão-obra). Impacto: drenagem profunda +30% vida pavimento reduzindo poropressão.', CEIL(LENGTH('Drenagem profunda — drenos longitudinais dentro aterro/base, capturam água freática. Composição: núcleo PEAD perfurado 100-150mm (captação), envoltório brita 5-10cm (filtro física), geotêxtil envolvente (retenção finos). Espaçamento: cada 20-50m (depende gradiente) ao longo rodovia. Posicionamento: linha máxima saturação esperada (levantamento piezômetro). Vazão: Q=k×A×i (k permeabilidade 10^-1 cm/s BGS, A seção dreno, i declividade 2-4%). Saída: boca-leão/dissipador pé talude ou bacia sedimentação (evita descarga brusca). Manutenção: limpeza cada 2-3 anos (risco obstrução silte), vácuo com bomba submersível. Custo: R$ 1.000-3.000/100m (tubo+brita+mão-obra). Impacto: drenagem profunda +30% vida pavimento reduzindo poropressão.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:drenagem_profunda', 'categoria', 'drenagem_profunda', 'section', '3', 'subsection', '3.1', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 10, 'Filtros geotêxtil — separação camadas, retenção finos, drenagem. Critério seleção: abertura malha (AOS) < 4× diâmetro solo retenção; permeabilidade (k) > k-solo para transmissão (k≥10^-1 cm/s). Tipos: tecido (resistência alta, custo -), não-tecido (flexibilidade alta, custo +). Aplicações: (1) sob dreno (retenção finos, k adequada), (2) entre base-subbase (evita eluição), (3) talude (erosão superficial). Especificação DNIT: NBR 6835, resistência tração ≥8 kN/m, rasgamento ≥4 kN. Dimensionamento: sobrepor 30cm entre painéis, ancoragem bordas (piquetes, sapata). Custo: R$ 3-8/m² (varia especificação). Impacto: geotêxtil inadequado colapsa (finos colmatam, reduz vazão), adequado estabiliza drenagem 20+ anos. Manutenção: visual pós-chuva (rasgamento), substituição se danificado.', CEIL(LENGTH('Filtros geotêxtil — separação camadas, retenção finos, drenagem. Critério seleção: abertura malha (AOS) < 4× diâmetro solo retenção; permeabilidade (k) > k-solo para transmissão (k≥10^-1 cm/s). Tipos: tecido (resistência alta, custo -), não-tecido (flexibilidade alta, custo +). Aplicações: (1) sob dreno (retenção finos, k adequada), (2) entre base-subbase (evita eluição), (3) talude (erosão superficial). Especificação DNIT: NBR 6835, resistência tração ≥8 kN/m, rasgamento ≥4 kN. Dimensionamento: sobrepor 30cm entre painéis, ancoragem bordas (piquetes, sapata). Custo: R$ 3-8/m² (varia especificação). Impacto: geotêxtil inadequado colapsa (finos colmatam, reduz vazão), adequado estabiliza drenagem 20+ anos. Manutenção: visual pós-chuva (rasgamento), substituição se danificado.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:filtros_geotextil', 'categoria', 'filtros_geotextil', 'section', '3', 'subsection', '3.2', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 11, 'Compactação com drenagem — desafio executivo: compactar (reduz vazios, aumenta k diminui) vs drenagem (vazios, k elevado). Solução: compactar camadas 30-50cm com passadas controladas (2-4 rolo, não excessivo), deixar dreno longitudinal em posição (não esmaga brita), verificar densímetro (não ultrapassar ρ_dmáx+5%). Sequência: espalhamento 30cm → compactação rolo + drenagem no fluxo → espalhamento próxima 30cm. Umidade crítica: ω_ótima±2% garante compactação sem colapso. Monitoramento: teste cone densidade cada 100m², piezômetro controla poropressão (deve reduzir com drenagem). Impacto erros: compactação excessiva + drenagem inadequada = pavimento úmido = falha precoce (afundamento, trincas). Norma DNIT 105/2009.', CEIL(LENGTH('Compactação com drenagem — desafio executivo: compactar (reduz vazios, aumenta k diminui) vs drenagem (vazios, k elevado). Solução: compactar camadas 30-50cm com passadas controladas (2-4 rolo, não excessivo), deixar dreno longitudinal em posição (não esmaga brita), verificar densímetro (não ultrapassar ρ_dmáx+5%). Sequência: espalhamento 30cm → compactação rolo + drenagem no fluxo → espalhamento próxima 30cm. Umidade crítica: ω_ótima±2% garante compactação sem colapso. Monitoramento: teste cone densidade cada 100m², piezômetro controla poropressão (deve reduzir com drenagem). Impacto erros: compactação excessiva + drenagem inadequada = pavimento úmido = falha precoce (afundamento, trincas). Norma DNIT 105/2009.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:compactacao_drenagem', 'categoria', 'compactacao_drenagem', 'section', '3', 'subsection', '3.3', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 12, 'Projeto drenagem integrado — combinação superficial + profunda + subsuperficial para máxima eficiência. Fluxograma: (1) levantamento hidrologia (curva IDF, bacias), (2) cálculo Q método racional/SCS, (3) projeto drenagem superficial (sarjetas, bueiros, dissipadores), (4) projeto drenagem profunda (drenos longitudinais), (5) verificação subsuperficial (geotêxtil, filtros), (6) modelagem HEC-HMS/SWMM (validação). Detalhes: integração sarjeta-bueiro (transição suave), sobreposição drenagem superficial-profunda (redundância segurança), espaçamento bueiro baseado em Q cada sub-bacia. Documentação: planos drenagem (planta, perfil, detalhes), especificação materiais, cronograma. Validação: simulação chuva de projeto, verificação alagamento pontos críticos (não deve ocorrer). Norma DNIT IPR 382/2020.', CEIL(LENGTH('Projeto drenagem integrado — combinação superficial + profunda + subsuperficial para máxima eficiência. Fluxograma: (1) levantamento hidrologia (curva IDF, bacias), (2) cálculo Q método racional/SCS, (3) projeto drenagem superficial (sarjetas, bueiros, dissipadores), (4) projeto drenagem profunda (drenos longitudinais), (5) verificação subsuperficial (geotêxtil, filtros), (6) modelagem HEC-HMS/SWMM (validação). Detalhes: integração sarjeta-bueiro (transição suave), sobreposição drenagem superficial-profunda (redundância segurança), espaçamento bueiro baseado em Q cada sub-bacia. Documentação: planos drenagem (planta, perfil, detalhes), especificação materiais, cronograma. Validação: simulação chuva de projeto, verificação alagamento pontos críticos (não deve ocorrer). Norma DNIT IPR 382/2020.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:projeto_integrado', 'categoria', 'projeto_integrado', 'section', '4', 'subsection', '4.1', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 13, 'Manutenção e diagnóstico drenagem — inspeção visual pós-chuva (sedimento, erosão), limpeza anual (varredura, vácuo). Problema comum: colmatação (finos sedimento, folhas), redução vazão, acúmulo água. Detecção: visualizar parado água em sarjeta >1h pós-chuva, ouvir reclamação alagamento. Solução: limpeza vácuo tubo dreno (caminhão-tanque), raspagem sedimento sarjeta, desobstrução boca-leão. Custo limpeza R$ 2.000-5.000/km (periódico). Diagnóstico avançado: câmera TV interna (tubulação), GPR (delimitação areia/obstrução). Impacto negligência: acúmulo água 2-3 anos → redução pavimento vida 40-50%, reabilitação custosa. Planejamento: contrato mantenedora com cláusula limpeza anual + verificação pós-chuva pesada. Sistema monitoramento: sensor nível água (alerta alagamento automático).', CEIL(LENGTH('Manutenção e diagnóstico drenagem — inspeção visual pós-chuva (sedimento, erosão), limpeza anual (varredura, vácuo). Problema comum: colmatação (finos sedimento, folhas), redução vazão, acúmulo água. Detecção: visualizar parado água em sarjeta >1h pós-chuva, ouvir reclamação alagamento. Solução: limpeza vácuo tubo dreno (caminhão-tanque), raspagem sedimento sarjeta, desobstrução boca-leão. Custo limpeza R$ 2.000-5.000/km (periódico). Diagnóstico avançado: câmera TV interna (tubulação), GPR (delimitação areia/obstrução). Impacto negligência: acúmulo água 2-3 anos → redução pavimento vida 40-50%, reabilitação custosa. Planejamento: contrato mantenedora com cláusula limpeza anual + verificação pós-chuva pesada. Sistema monitoramento: sensor nível água (alerta alagamento automático).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:manutencao_diagnostico', 'categoria', 'manutencao_diagnostico', 'section', '4', 'subsection', '4.2', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 14, 'Problemas comuns e soluções — alagamento pista (chuva moderada): causa insuficiente drenagem superficial ou bueiros entupidos; solução limpeza + dimensionamento novo bueiro. Erosão talude (chuva forte): inadequada contenção, inadequado dissipador; solução gavião + bacia amortecimento. Infiltração base-asfalto (umidade): drenagem profunda ineficaz, impermeabilização falha; solução nova drenagem longitudinal + reforço base. Recalque aterro (assentamento): drenagem inadequada compactação, poropressão alta; solução drenar profundo + recompactar. Caso BR-116 km 420-422 SP: SST (sedimento suspenso) 320 mg/L em chuva vs 100 mg/L limite CONAMA; solução bacia sedimentação + filtro geotêxtil entrada bueiro. Custo solução: R$ 5.000-50.000 (conforme severidade, extensão). Prevenção: projeto drenagem robusto (+20% custo obra, -50% manutenção 10 anos).', CEIL(LENGTH('Problemas comuns e soluções — alagamento pista (chuva moderada): causa insuficiente drenagem superficial ou bueiros entupidos; solução limpeza + dimensionamento novo bueiro. Erosão talude (chuva forte): inadequada contenção, inadequado dissipador; solução gavião + bacia amortecimento. Infiltração base-asfalto (umidade): drenagem profunda ineficaz, impermeabilização falha; solução nova drenagem longitudinal + reforço base. Recalque aterro (assentamento): drenagem inadequada compactação, poropressão alta; solução drenar profundo + recompactar. Caso BR-116 km 420-422 SP: SST (sedimento suspenso) 320 mg/L em chuva vs 100 mg/L limite CONAMA; solução bacia sedimentação + filtro geotêxtil entrada bueiro. Custo solução: R$ 5.000-50.000 (conforme severidade, extensão). Prevenção: projeto drenagem robusto (+20% custo obra, -50% manutenção 10 anos).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:problemas_solucoes', 'categoria', 'problemas_solucoes', 'section', '4', 'subsection', '4.3', 'collection_slug', 'rodovias-drenagem')
  UNION ALL SELECT 15, 'Qualidade água em drenagem — parâmetros CONAMA 357/430: SST (sedimento suspenso) ≤100 mg/L (classe 2), turbidez ≤40 UNT, óleos ≤0.3 mg/L, DBO₅ ≤5 mg/L. Monitoramento: coleta amostras entrada/saída drenagem (3 eventos chuva), análise laboratório ABNT ISO 5667. Impacto: descarga SST elevada prejudica corpos hídricos (assoreamento), rejeição licença ambiental. Mitigação: bacia sedimentação (repouso 30 min, remove >80% SST), filtro geotêxtil (capta finos), separador óleo-água (bombas/maquinário). Legislação: CONAMA 357, lei estadual (mais restritivo), RIMA licença ambiental. Exemplo: 100km rodovia SST médio 200 mg/L → bacia sedimentação reduz 150 mg/L → conforme CONAMA. Custo monitoramento R$ 3.000-8.000/ano (amostragem + análise). Responsabilidade: concedente/empreiteira até 5 anos pós-obra.', CEIL(LENGTH('Qualidade água em drenagem — parâmetros CONAMA 357/430: SST (sedimento suspenso) ≤100 mg/L (classe 2), turbidez ≤40 UNT, óleos ≤0.3 mg/L, DBO₅ ≤5 mg/L. Monitoramento: coleta amostras entrada/saída drenagem (3 eventos chuva), análise laboratório ABNT ISO 5667. Impacto: descarga SST elevada prejudica corpos hídricos (assoreamento), rejeição licença ambiental. Mitigação: bacia sedimentação (repouso 30 min, remove >80% SST), filtro geotêxtil (capta finos), separador óleo-água (bombas/maquinário). Legislação: CONAMA 357, lei estadual (mais restritivo), RIMA licença ambiental. Exemplo: 100km rodovia SST médio 200 mg/L → bacia sedimentação reduz 150 mg/L → conforme CONAMA. Custo monitoramento R$ 3.000-8.000/ano (amostragem + análise). Responsabilidade: concedente/empreiteira até 5 anos pós-obra.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:dren:qualidade_agua', 'categoria', 'qualidade_agua', 'section', '4', 'subsection', '4.4', 'collection_slug', 'rodovias-drenagem')
) chunks;

COMMIT;

-- Verification
SELECT
  COUNT(*) as total_chunks,
  COUNT(DISTINCT metadados_chunk->>'prefix_storage') as distinct_prefixes,
  (SELECT COUNT(*) FROM manta_rag_documents WHERE doc_id = 'rod-dren-especializacoes-20260804') as documents_created
FROM manta_rag_chunks
WHERE doc_id = 'rod-dren-especializacoes-20260804';
