-- WF-AKP-001 — INSERT de 36 teses aprovadas (gate humano 05/07/2026)

-- Executar APÓS a migration_teses_academicas.sql


INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2021-UFC-002', 'Earthworks Planning Using Optimization Techniques: Literature Analysis and Solution Proposal', 'Pedro G.P.S. Fernandes', 'UFC', 'mestrado', 2021, 'https://repositorio.ufc.br/bitstream/riufc/60836/1/2021_dis_pgpsfernandes.pdf', ARRAY['03-S1','05','07'], 'B1', 0, 'pass', '[{"id": "KE-001", "tipo": "metodo", "desc": "Modelo MILP terraplenagem+pavimentação+haul roads com restrições geotécnicas. 121 cortes, 257 aterros, solução em 2.98s", "tese_id": "TESE-2021-UFC-002"}, {"id": "KE-002", "tipo": "benchmark", "desc": "Systematic mapping 72 papers (1958-2021): LP/MILP dominam allocation, GA domina fleet/routing", "tese_id": "TESE-2021-UFC-002"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2012-UP-001', 'Distribuição de Terras Usando uma Extensão da Teoria de Brückner', 'Maria Manuela Ramalho de Mesquita', 'U.Porto/FEUP', 'mestrado', 2012, 'https://repositorio-aberto.up.pt/bitstream/10216/68372/1/000155026.pdf', ARRAY['03-S1'], 'B1', 0, 'pass', '[{"id": "KE-007", "tipo": "metodo", "desc": "Extensão do método Brückner incorporando condicionantes geotécnicas, ambientais e temporais. Múltiplas curvas de Brückner para cada imposição. Caso real: troço de autoestrada", "tese_id": "TESE-2012-UP-001"}, {"id": "KE-008", "tipo": "parametro", "desc": "Custos de equipamentos de transporte por tipologia, relacionados com material e inclinação do percurso", "tese_id": "TESE-2012-UP-001"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2017-USP-TBM', 'Túneis escavados em solo por máquina tuneladora: conceituação, comportamento do maciço e modelagem numérica', 'Gustavo Aguiar', 'USP Poli', 'mestrado', 2017, 'https://teses.usp.br/teses/disponiveis/3/3145/tde-21062017-132502/publico/GustavoAguiarCorr17.pdf', ARRAY['03-S4'], 'B6', 0, 'pass', '[{"id": "KE-003", "tipo": "metodo", "desc": "Diretrizes FEM Plaxis 2D para TBM/EPB: alívio tensões vs contração, Mohr-Coulomb vs Hardening Soil, revestimento com/sem juntas", "tese_id": "TESE-2017-USP-TBM"}, {"id": "KE-004", "tipo": "parametro", "desc": "Parâmetros Hardening Soil para solos SP: E50_ref, Eur_ref, coef. m. Retroanálise caso real", "tese_id": "TESE-2017-USP-TBM"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2018-IST-NATM', 'Túnel de Águas Santas: análise do comportamento em fase de obra', 'Margarida Ferreira Pinto Afonso e Cunha', 'IST Lisboa', 'mestrado', 2018, 'https://fenix.tecnico.ulisboa.pt/downloadFile/844820067126122/Dissertacao_Final_70112.pdf', ARRAY['03-S4'], 'B6', 0, 'pass', '[{"id": "KE-009", "tipo": "metodo", "desc": "Retroanálise NATM em maciço granítico com Plaxis 2D + Hoek-Brown. RMR da frente de escavação validado com instrumentação. Faseamento: calote + rebaixo", "tese_id": "TESE-2018-IST-NATM"}, {"id": "KE-010", "tipo": "case_study", "desc": "Túnel A4 Porto/Amarante — dados reais de monitorização + back analysis. GSI, RQD, SPT correlacionados", "tese_id": "TESE-2018-IST-NATM"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2020-UFPE-001', 'Procedimento Adaptativo de Correção de Contra Flecha em Pontes em Balanços Sucessivos — Monte Carlo + Fluência', 'Mariella Falcão de Lima Oliveira Santos', 'UFPE', 'doutorado', 2020, 'https://repositorio.ufpe.br/bitstream/123456789/38379/1/TESE%20Mariella%20Falc%C3%A3o%20de%20Lima%20Oliveira%20Santos.pdf', ARRAY['03-S2','07'], 'B8', 0, 'pass', '[{"id": "KE-005", "tipo": "metodo", "desc": "Monte Carlo adaptativo para contra flecha em balanço sucessivo, com otimização por Mínimos Quadrados e incerteza de fluência", "tese_id": "TESE-2020-UFPE-001"}, {"id": "KE-006", "tipo": "formula", "desc": "Modelo estocástico de fluência CEB-FIP/NBR 6118 para diferentes idades com quantificação de incerteza", "tese_id": "TESE-2020-UFPE-001"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2016-IST-LEAN', 'Lean na Construção: Estado atual, Desafios e Técnicas prioritárias a aplicar em Portugal', 'Patrick Pequito Aparício', 'IST Lisboa', 'mestrado', 2016, 'https://fenix.tecnico.ulisboa.pt/downloadFile/1689244997256275/Dissertacao%20-%20(%20Documento%20Final%20Revisto)%20Patrick%20Pequito%20Aparicio.pdf', ARRAY['07'], 'B4', 0, 'pass', '[{"id": "KE-011", "tipo": "benchmark", "desc": "Survey + Workshop com indústria PT: 5 técnicas Lean prioritárias identificadas (VSM, Instruções de Trabalho, Reuniões Performance, TVD, BIM)", "tese_id": "TESE-2016-IST-LEAN"}, {"id": "KE-012", "tipo": "metodo", "desc": "Framework de implementação Lean Construction com mapeamento de ineficiências por fase do empreendimento", "tese_id": "TESE-2016-IST-LEAN"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('REF-2000-BIRM-BALLARD', 'The Last Planner System of Production Control', 'Herman Glenn Ballard', 'University of Birmingham', 'doutorado', 2000, 'https://etheses.bham.ac.uk/id/eprint/4789/', ARRAY['07'], 'B4', 0, 'pass', '[{"id": "KE-013", "tipo": "metodo", "desc": "Tese seminal do Last Planner System: PPC (Percent Plan Complete), lookahead planning, constraint analysis, weekly work plans. Base do Lean Construction mundial", "tese_id": "REF-2000-BIRM-BALLARD"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('REF-2000-HUT-KOSKELA', 'An exploration towards a production theory and its application to construction', 'Lauri Koskela', 'Helsinki University of Technology', 'doutorado', 2000, 'https://aaltodoc.aalto.fi/', ARRAY['07','15'], 'B4', 0, 'pass', '[{"id": "KE-014", "tipo": "metodo", "desc": "Teoria TFV (Transformation-Flow-Value): fundamento teórico do Lean Construction. Construção não é só transformação — fluxo e valor são igualmente críticos", "tese_id": "REF-2000-HUT-KOSKELA"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2024-UFAL-EPANET', 'Modelagem e simulação hidráulica do sistema de abastecimento de água com uso de tecnologia GIS e EPANET: estudo de caso Piaçabuçu/AL', 'Hítila Ribeiro Correia', 'UFAL', 'mestrado', 2024, 'https://www.repositorio.ufal.br/bitstream/123456789/16342/1/', ARRAY['03-S8'], 'B7', 0, 'pass', '[{"id": "KE-015", "tipo": "metodo", "desc": "Pipeline GIS + EPANET 2.0 para modelagem hidráulica de rede de distribuição com dados reais de companhia de saneamento. Metodologia replicável para AySA", "tese_id": "TESE-2024-UFAL-EPANET"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2018-PMWJ-TIA', 'Effective Tactics for Delay Analysis — TIA Methods Comparison', 'Pratyush K. Chaturvedi', 'SKEMA Business School / PM World Journal', 'paper', 2018, 'https://pmworldlibrary.net/wp-content/uploads/2018/12/pmwj77-Dec2018-Chaturvedi-effective-tactices-for-delay-analysis.pdf', ARRAY['07','01'], 'B2', 7.8, 'pass', '[{"id": "KE-016", "tipo": "metodo", "desc": "Comparação TIA prospectiva vs retrospectiva (AACE RP 29R-03). MIP 3.3-3.7 detalhados. TIA é a técnica mais precisa. Aplicação em Oil&Gas EPC com CPM schedule atualizado.", "tese_id": "ART-2018-PMWJ-TIA"}, {"id": "KE-017", "tipo": "benchmark", "desc": "Tabela comparativa: As-Planned vs As-Built, Impacted As-Planned, Collapsed As-Built, Window Analysis, TIA — quando usar cada uma", "tese_id": "ART-2018-PMWJ-TIA"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-SPIRE-MM-POWER', 'Quantifying Disruption in Power Projects Using the Measured Mile Analysis', 'Spire Consulting Group', 'Spire Consulting Group', 'paper', 2021, 'https://www.spireconsultinggroup.com/wp-content/uploads/2021/09/Quantifying-Disruption-in-Power-Projects-Using-Measured-Mile.pdf', ARRAY['01','02-C'], 'B5', 9.4, 'pass', '[{"id": "KE-018", "tipo": "metodo", "desc": "Pipeline completo Measured Mile em 5 etapas: (1) Identificar atividades impactadas, (2) Compilar dados de produtividade, (3) Identificar Measured Mile (período não impactado), (4) Calcular lost man-hours, (5) Totalizar danos. Fórmulas: Productivity = Units/MH, PF = BaselineProd/ActualProd, Lost MH = (Actual - Baseline) × Units", "tese_id": "ART-SPIRE-MM-POWER"}, {"id": "KE-019", "tipo": "case_study", "desc": "Case study: Disruption claim em power plant global. Piping installation como atividade-chave. Gráfico de produtividade por período com identificação visual do Measured Mile. Claim bem-sucedido.", "tese_id": "ART-SPIRE-MM-POWER"}, {"id": "KE-020", "tipo": "benchmark", "desc": "AACE RP 25R-03 lista 25 causas de perda de produtividade. Nexo disruption→ripple effects→cumulative impact→lost productivity. Timing e quantum do change afetam severidade.", "tese_id": "ART-SPIRE-MM-POWER"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2022-CDNSCI-MAPPING', 'Optimization of earthworks planning: a systematic mapping study (71 papers, 1958-2021)', 'Canadian J. Civil Engineering', 'Canadian Science Publishing', 'paper', 2022, 'https://cdnsciencepub.com/doi/10.1139/cjce-2022-0185', ARRAY['03-S1','05'], 'B1', 9.0, 'pass', '[{"id": "KE-021", "tipo": "benchmark", "desc": "Mapping 5785→71 papers earthwork optimization. Allocation, fleet planning, routing, scheduling são os tópicos mais investigados. LP, MILP, GA as técnicas mais usadas. Modelos com fatores construtivos melhoram orçamentos e planos de transporte.", "tese_id": "ART-2022-CDNSCI-MAPPING"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2024-ASCE-HAUL', 'Optimization Model for Earthwork Allocations Considering Multiple Haul Roads: GIS-Based Integrated Approach', 'ASCE J. Construction Eng. Management', 'ASCE', 'paper', 2024, 'https://ascelibrary.org/doi/10.1061/JCEMD4.COENG-13922', ARRAY['03-S1'], 'B1', 9.2, 'pass', '[{"id": "KE-022", "tipo": "metodo", "desc": "Modelo GIS-based para alocação de terraplenagem com múltiplos haul roads. Integra topografia, distâncias reais (não euclidianas) e custos de abertura de caminhos. Avanço sobre modelos LP tradicionais.", "tese_id": "ART-2024-ASCE-HAUL"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2024-L2V-METRO', 'Instrumentação geotécnica TBM Linha 2-Verde Metrô SP (Vila Formosa–Coxim, 2024)', 'Caderno Pedagógico', 'Caderno Pedagógico', 'paper', 2024, 'https://ojs.studiespublicacoes.com.br/ojs/index.php/cadped/article/view/4845', ARRAY['03-S4'], 'B6', 9.0, 'pass', '[{"id": "KE-023", "tipo": "case_study", "desc": "Dados reais 2024 de recalques TBM na Linha 2-Verde Metrô SP. Comparação recalques previstos vs observados via marcos superficiais e tassômetros. Diretamente aplicável como benchmark para L5 e L6.", "tese_id": "ART-2024-L2V-METRO"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2023-REBEP-PRIV', 'Impacto da privatização da água e esgoto nas tarifas e acesso no Brasil (1998-2019, 3.536 municípios)', 'Larissa S. Côrtes et al.', 'REBEP / UFMG', 'paper', 2023, 'https://rebep.org.br/revista/article/view/2238', ARRAY['03-S8','15'], 'B7', 9.4, 'pass', '[{"id": "KE-024", "tipo": "benchmark", "desc": "Diff-in-diff com 3.536 municípios SNIS (1998-2019): prestadores privados têm impacto positivo e significativo em cobertura de água, esgoto e tratamento. Tarifas também sobem. Lei 14.026/2020. Diretamente aplicável à análise AySA.", "tese_id": "ART-2023-REBEP-PRIV"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('REF-SINAPI-MANUAL', 'SINAPI — Manual de Metodologias e Conceitos (CEF/IBGE)', 'Caixa Econômica Federal / IBGE', 'CEF', 'norma', 2024, 'https://files.cercomp.ufg.br/weby/up/124/o/SINAPI_Manual_de_Metodologias_e_Conceitos_v002.pdf', ARRAY['05'], 'B3', 9.8, 'pass', '[{"id": "KE-025", "tipo": "norma", "desc": "Manual completo SINAPI: CHP e CHI de equipamentos, composições de custo horário de mão de obra (alimentação, transporte, EPI, ferramentas, exames, seguros), encargos sociais complementares, aferição de produtividade por grupo de serviços.", "tese_id": "REF-SINAPI-MANUAL"}, {"id": "KE-026", "tipo": "parametro", "desc": "Fórmulas de custo horário: CHP (produtivo) e CHI (improdutivo). Variáveis: vida útil, depreciação, manutenção, combustível, lubrificantes, pneus. Fator de disponibilidade 1.25.", "tese_id": "REF-SINAPI-MANUAL"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('REF-SICRO-CUSTOS-ENAP', 'Introdução à Orçamentação de Obras Rodoviárias — Composição de Custos (ENAP/DNIT)', 'ENAP / DNIT', 'ENAP', 'norma', 2021, 'https://repositorio.enap.gov.br/jspui/bitstream/1/7644/3/M%C3%B3dulo%202%20-%20Composi%C3%A7%C3%A3o%20de%20Custos.pdf', ARRAY['05','03-S1'], 'B3', 9.6, 'pass', '[{"id": "KE-027", "tipo": "metodo", "desc": "Pipeline completo de composição de custos SICRO: (1) custo horário equipamentos, (2) mão de obra com encargos, (3) materiais com fator de conversão, (4) BDI diferenciado por faixa. IS/DG nº 44/2021 para Preços Novos.", "tese_id": "REF-SICRO-CUSTOS-ENAP"}, {"id": "KE-028", "tipo": "parametro", "desc": "Fator de conversão corte→solto para terraplenagem. BDI diferenciado: faixas por natureza do serviço (inovação SICRO vs SICRO 2). Decreto 7.983/2013 como base legal.", "tese_id": "REF-SICRO-CUSTOS-ENAP"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-BARREIROS-CHP', 'Custo Horário de Equipamentos: SINAPI × SICRO — Comparativo', 'Felipe Barreiros', 'UNISUL', 'paper', 2020, 'https://repositorio.animaeducacao.com.br/bitstream/ANIMA/8772/1/Custo%20Hor%C3%A1rio%20de%20Equipamentos%20SINAPI%20X%20SICRO.pdf', ARRAY['05'], 'B3', 7.6, 'pass', '[{"id": "KE-029", "tipo": "benchmark", "desc": "Comparativo detalhado SINAPI vs SICRO para custo horário de equipamentos: diferenças em depreciação (fator disponibilidade 1.25 SINAPI vs produtividade SICRO), manutenção, vida útil. Mesma tabela de vida útil base, mas tratamento diferente.", "tese_id": "ART-BARREIROS-CHP"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-UNIGRANRIO-MC', 'Avaliação Probabilística de Cronogramas de Projetos — Simulação Monte Carlo para Descomissionamento', 'Thiago de Souza Silva', 'UNIGRANRIO', 'mestrado', 2022, 'https://portal.unigranrio.edu.br/hubfs/Disserta%C3%A7%C3%A3o%20Thiago%20Silva_Final.pdf', ARRAY['07'], 'B2', 7.8, 'pass', '[{"id": "KE-030", "tipo": "metodo", "desc": "Monte Carlo com distribuição Beta para durações de atividades em cronogramas. Comparativo PERT determinístico vs SMC probabilístico. Tabela de durações previstas vs simuladas com desvios.", "tese_id": "TESE-UNIGRANRIO-MC"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2024-ICRA-MC', 'Avaliação de riscos de prazos — Simulação Monte Carlo com Índice de Criticidade de Risco de Atraso (ICRA)', 'Caderno Pedagógico', 'Caderno Pedagógico', 'paper', 2024, 'https://ojs.studiespublicacoes.com.br/ojs/index.php/cadped/article/view/3471', ARRAY['07'], 'B2', 8.4, 'pass', '[{"id": "KE-031", "tipo": "metodo", "desc": "ICRA (Índice de Criticidade de Risco de Atraso) por atividade do caminho crítico + Monte Carlo com @RISK Industrial para probabilidade global de término. Modelo retroalimentável durante execução. Prático para gestores.", "tese_id": "ART-2024-ICRA-MC"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2024-PYTHON-MC', 'Simulação Monte Carlo como ferramenta para análise de risco no gerenciamento de projetos — algoritmo Python', 'Herzog, Silva, Weymar', 'UNINOVE / Dialnet', 'paper', 2024, 'https://dialnet.unirioja.es/descarga/articulo/9850643.pdf', ARRAY['07'], 'B2', 8.6, 'pass', '[{"id": "KE-032", "tipo": "metodo", "desc": "Algoritmo Python para Monte Carlo em cronogramas de construção. Implementação open-source replicável. Integra distribuição triangular + CPM + análise de risco. Diretamente integrável ao agente M07.", "tese_id": "ART-2024-PYTHON-MC"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-UTFPR-CPM-MC', 'Análise comparativa de assertividade dos métodos CPM e Simulação de Monte Carlo para cronogramas de construção civil', 'UTFPR', 'Universidade Tecnológica Federal do Paraná', 'mestrado', 2020, 'https://repositorio.utfpr.edu.br/jspui/handle/1/27489', ARRAY['07'], 'B2', 8.2, 'pass', '[{"id": "KE-033", "tipo": "benchmark", "desc": "Comparação empírica CPM determinístico vs Monte Carlo probabilístico em projetos reais de construção civil. Monte Carlo superior na assertividade de previsão de prazo.", "tese_id": "TESE-UTFPR-CPM-MC"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2021-UNB-REEQ', 'Contratos de concessões de rodovias federais: análise dos pedidos de revisões extraordinárias com vistas ao reequilíbrio econômico-financeiro', 'Lisandro Cogo Beck', 'Universidade de Brasília', 'mestrado', 2021, 'https://repositorio.unb.br/bitstream/10482/41363/1/2021_LisandroCogoBeck.pdf', ARRAY['01','02-C','15'], 'B5', 9.4, 'pass', '[{"id": "KE-034", "tipo": "case_study", "desc": "Análise de pedidos de revisões extraordinárias em concessões rodoviárias federais. Mapeamento dos principais gatilhos de reequilíbrio, metodologias adotadas pela ANTT, e impactos na TIR. Diretamente aplicável a claims em concessões Manta.", "tese_id": "TESE-2021-UNB-REEQ"}, {"id": "KE-035", "tipo": "norma", "desc": "Resolução ANTT 5.850/2019: procedimentos para reequilíbrio econômico-financeiro. Fluxo de Caixa Marginal como método. Decreto 7.983/2013 como base legal.", "tese_id": "TESE-2021-UNB-REEQ"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-2014-UNESP-EEF', 'O equilíbrio econômico-financeiro dos contratos de concessão de rodovias federais e estaduais sob a égide da Lei 8.987/95', 'Fernanda de Mello Matos', 'UNESP — Faculdade de Ciências Humanas e Sociais', 'mestrado', 2014, 'https://repositorio.unesp.br/items/fea2b5af-fd2c-45ce-8bd8-6c818f012b6c', ARRAY['01','02-C','15'], 'B5', 8.6, 'pass', '[{"id": "KE-036", "tipo": "metodo", "desc": "Framework jurídico completo do EEF em concessões rodoviárias: Lei 8.987/95, evolução Procrofe (Fases I-III), posicionamento TCU, matriz de riscos, Fator D para reequilíbrio por atraso em obras de ampliação.", "tese_id": "TESE-2014-UNESP-EEF"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-FGV-EEF-RODOVIAS', 'O equilíbrio econômico-financeiro nas concessões de rodovias federais', 'FGV Direito Rio', 'FGV', 'paper', 2017, 'https://editoraforum.com.br/wp-content/uploads/2017/07/equilibrio-financeiro-concessoes.pdf', ARRAY['01','02-C','06','15'], 'B5', 9.2, 'pass', '[{"id": "KE-037", "tipo": "metodo", "desc": "Evolução do racional econômico nas 3 fases do Procrofe. Desconto de reequilíbrio, indicadores de desempenho, gatilhos de investimentos, Fluxo de Caixa Marginal. Posicionamento TCU. Framework completo para modelagem de concessões.", "tese_id": "ART-FGV-EEF-RODOVIAS"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('REF-TCEMG-REEQ', 'Estudo Técnico: O Instituto do Reequilíbrio Econômico-Financeiro (TCE-MG)', 'Tribunal de Contas do Estado de Minas Gerais', 'TCE-MG', 'norma', 2023, 'https://www.tce.mg.gov.br/IMG/2023/Estudo-tecnico-Reequilibrio-Economico-Financeiro-Paginas-Individuais.pdf', ARRAY['01','02-C'], 'B5', 9.0, 'pass', '[{"id": "KE-038", "tipo": "norma", "desc": "Estudo completo do TCE-MG sobre reequilíbrio: Lei 8.666/93, Lei 14.133/2021, Lei 13.303/16. Variação cambial, reajuste vs revisão, limites da álea. 11 parâmetros do TCE-SC para concessão de reequilíbrio em infraestrutura rodoviária.", "tese_id": "REF-TCEMG-REEQ"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-FGV-EPGE-REEQ', 'Avaliação da proposta de readaptação e otimização de concessões rodoviárias (FGV EPGE)', 'FGV EPGE / BNDES', 'FGV EPGE', 'mestrado', 2022, 'https://web.bndes.gov.br/bib/jspui/bitstream/1408/26907/1/PRTese_216427_Avalia%C3%A7%C3%A3o%20da%20proposta%20de%20readapta%C3%A7%C3%A3o%20e%20otimiza%C3%A7%C3%A3o.pdf', ARRAY['06','15'], 'B5', 9.0, 'pass', '[{"id": "KE-039", "tipo": "metodo", "desc": "Teoria econômica de renegociação de concessões: diferença entre reequilíbrio contratual e renegociação. Impacto da alteração da matriz de risco. Análise das 3 fases do Procrofe com lente econômica. Aplicável a modelagem financeira de concessões.", "tese_id": "TESE-FGV-EPGE-REEQ"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('TESE-PHD-MITRE-OAE', 'Metodologia para Inspeção e Diagnóstico de Pontes e Viadutos de Concreto', 'Marcos Pedrosa Mitre', 'PHD Engenharia / USP', 'mestrado', 2005, 'https://phd.eng.br/wp-content/uploads/2017/04/Mestrado_MarcosMitre.pdf', ARRAY['03-S2'], 'B8', 9.0, 'pass', '[{"id": "KE-040", "tipo": "metodo", "desc": "Metodologia de inspeção e diagnóstico de OAEs: classificação de gravidade/extensão/intensidade, graus de urgência, custos reais de manutenção (dados Ecovias). Norma DNIT 010-PRO integrada. Aplicável ao SGO e gestão de OAEs em concessões.", "tese_id": "TESE-PHD-MITRE-OAE"}, {"id": "KE-041", "tipo": "benchmark", "desc": "Custos reais de recuperação de OAEs em concessionárias (Ecovias, Autopistas). Dados de 332 pontes e viadutos analisados com incidência de patologias: infiltrações 88%, desplacamento 53%, armaduras expostas 52%.", "tese_id": "TESE-PHD-MITRE-OAE"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-GDE-UNB-OAE', 'Avaliação teórica das metodologias de inspeção visual de OAE: NBR 9452 vs DNIT 010-PRO vs GDE/UnB', 'ResearchGate / Vários', 'UnB / Vários', 'paper', 2020, 'https://www.researchgate.net/publication/343324993', ARRAY['03-S2'], 'B8', 8.8, 'pass', '[{"id": "KE-042", "tipo": "benchmark", "desc": "Comparação das 3 metodologias de inspeção de OAE: NBR 9452 (ABNT), DNIT 010-PRO, GDE/UnB. GDE/UnB reduz subjetividade via fatores de ponderação+intensidade+grau de dano. As 3 usam escala 1-5. GDE/UnB mais precisa para gestão de portfólio.", "tese_id": "ART-GDE-UNB-OAE"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2025-ANPEC-PRIV', 'Efeitos da privatização nos serviços de água e esgoto — análise pós Novo Marco Legal (ANPEC 2025)', 'ANPEC 2025', 'ANPEC', 'paper', 2025, 'https://www.anpec.org.br/encontro/2025/submissao/files_I/i5-d9b240c7351017d49bbf55a1af279d4b.pdf', ARRAY['03-S8','15'], 'B7', 9.2, 'pass', '[{"id": "KE-043", "tipo": "benchmark", "desc": "Análise pós-NMLSB (Lei 14.026/2020): privatização promove ganhos gerenciais mas efeitos sobre universalização dependem do desenho contratual. Modelos baseados em menor tarifa + metas de qualidade > modelos focados em outorgas. >100 concessões/ano pós-2021. Aumento tarifário comprovado nos early adopters.", "tese_id": "ART-2025-ANPEC-PRIV"}, {"id": "KE-044", "tipo": "case_study", "desc": "Dados SNIS municipais: comparação prestadores públicos vs privados em perdas físicas, eficiência energética, cobertura. Evidência empírica para calibrar expectativas AySA.", "tese_id": "ART-2025-ANPEC-PRIV"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-SCIELO-PRIV-4CASOS', 'Privatização do saneamento no Brasil: quatro experiências e muitas lições (Limeira, Prolagos, Juturnaíba, Petrópolis)', 'SciELO / Nova Economia', 'SciELO', 'paper', 2005, 'https://scielo.br/scielo.php?pid=S1413-80502005000300009&script=sci_arttext', ARRAY['03-S8','15'], 'B7', 8.8, 'pass', '[{"id": "KE-045", "tipo": "case_study", "desc": "4 casos reais de privatização saneamento BR: Limeira (concessão plena), Prolagos e Juturnaíba (Região dos Lagos RJ), Petrópolis (subconcessão). Estrutura tarifária escalonada, outorga, TRA básica R$0.45. Lições sobre desenho contratual.", "tese_id": "ART-SCIELO-PRIV-4CASOS"}, {"id": "KE-046", "tipo": "parametro", "desc": "Evolução tarifária pré/pós privatização por município. Faixas de consumo, conta mínima, tarifa social. Benchmark direto para modelagem AySA.", "tese_id": "ART-SCIELO-PRIV-4CASOS"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-IPPUR-IGUA-RJ', 'Privatização do saneamento e desigualdades ambientais na metrópole carioca — caso Iguá/CEDAE', 'IPPUR/UFRJ', 'IPPUR/UFRJ', 'paper', 2025, 'https://ippur.ufrj.br/privatizacao-do-saneamento-e-desigualdades-ambientais-na-metropole-carioca/', ARRAY['03-S8','15'], 'B7', 8.4, 'pass', '[{"id": "KE-047", "tipo": "case_study", "desc": "Caso Iguá/CEDAE Rio de Janeiro: paralisação ETE Barra da Tijuca, desigualdade na aplicação da legislação, Coletores de Tempo Seco (CTS). Riscos de gestão privada sem regulação rigorosa. Contraponto relevante para análise AySA.", "tese_id": "ART-IPPUR-IGUA-RJ"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2025-NATURE-EVM', 'Comparative analysis of earned value management techniques in construction projects (Scientific Reports / Nature)', 'Scientific Reports', 'Nature / Scientific Reports', 'paper', 2025, 'https://www.nature.com/articles/s41598-025-05834-z', ARRAY['07','05'], 'B4', 9.6, 'pass', '[{"id": "KE-048", "tipo": "benchmark", "desc": "Comparação de 3 técnicas EVM em 30 projetos reais (Egito): Earned Duration, Earned Schedule, Planned Value. Earned Schedule mais preciso no início; Earned Duration mais preciso em estágios avançados. Dataset de 30 projetos como benchmark.", "tese_id": "ART-2025-NATURE-EVM"}, {"id": "KE-049", "tipo": "metodo", "desc": "Framework de seleção de técnica EVM por tipo de projeto e estágio de progresso. Métricas: CPI, SPI, EAC, ETC, VAC. Importância de considerar tipo de projeto ao selecionar método.", "tese_id": "ART-2025-NATURE-EVM"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2022-MDPI-EVM', 'Earned Value Method for Construction: Current Application and Future Projections (MDPI Buildings)', 'Proaño-Narváez et al.', 'MDPI Buildings', 'paper', 2022, 'https://www.mdpi.com/2075-5309/12/3/301', ARRAY['07','05'], 'B4', 8.4, 'pass', '[{"id": "KE-050", "tipo": "case_study", "desc": "EVM aplicado a projetos reais em Cuenca/Equador. Reconstrução de eventos passados via database. Curva S original vs final. Métricas PV/EV/AC ao longo do tempo. VAC%=-3.24% de overrun. Demonstra aplicabilidade em construção civil latino-americana.", "tese_id": "ART-2022-MDPI-EVM"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2024-ML-EVM', 'Evaluation of EVM-Based Cost Estimation via Machine Learning (MDPI Buildings)', 'MDPI Buildings', 'MDPI Buildings', 'paper', 2024, 'https://www.mdpi.com/2075-5309/14/12/3772', ARRAY['07','05','16'], 'B4', 9.0, 'pass', '[{"id": "KE-051", "tipo": "metodo", "desc": "19 métodos EAC calculados + ML (Machine Learning) para previsão de custo final em obras. Dados reais: 122 dias monitorados diariamente, 13 atividades. ML melhora previsão vs EVM tradicional. Integrável ao M16 pesquisador evolutivo.", "tese_id": "ART-2024-ML-EVM"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;

INSERT INTO teses_academicas (codigo, titulo, autor, instituicao, grau, ano, url_original, agentes_destino, bloco_busca, grader_score, aluci_status, conhecimentos)
VALUES ('ART-2011-SCIDIR-MASSHAULBAL', 'Developing an efficient algorithm for balancing mass-haul diagrams (Automation in Construction)', 'Nassar, Hosny', 'ScienceDirect / Automation in Construction', 'paper', 2011, 'https://www.sciencedirect.com/science/article/abs/pii/S0926580511000744', ARRAY['03-S1'], 'B1', 9.0, 'pass', '[{"id": "KE-052", "tipo": "metodo", "desc": "Algoritmo automático para balancear diagramas de massa usando shortest-haul-first. Pruning sequencial do mass diagram. 70% dos construction managers usam mass-haul diagram (survey). Supera limitações do balanceamento manual/gráfico e do Civil 3D (que não oferece balanceamento).", "tese_id": "ART-2011-SCIDIR-MASSHAULBAL"}]'::jsonb)
ON CONFLICT (codigo) DO UPDATE SET grader_score = EXCLUDED.grader_score, conhecimentos = EXCLUDED.conhecimentos, aluci_status = EXCLUDED.aluci_status;