#!/usr/bin/env python3
"""
Weekly Feedback Analysis — Data Team continuous-improvement job.

Wraps analyze_feedback_and_recommend() (see
supabase/migrations/2026_07_26_add_feedback_tables.sql) to produce:
  1. A weekly approval-rate report per agent.
  2. Concrete keyword boost/demotion recommendations.
  3. Optional GitHub issues for HIGH priority recommendations.

Usage:
    python scripts/weekly_feedback_report.py
    python scripts/weekly_feedback_report.py --since 2026-07-19 --until 2026-07-26
    python scripts/weekly_feedback_report.py --create-issues --repo manta/manta-hub
    python scripts/weekly_feedback_report.py --dry-run
"""

import os
import sys
import argparse
from datetime import date, timedelta
from typing import Optional

try:
    from supabase import create_client, Client
except ImportError:
    print("Missing dependency. Install with: pip install supabase")
    sys.exit(1)


def get_client() -> Client:
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_ANON_KEY")
    if not url or not key:
        print("SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set")
        sys.exit(1)
    return create_client(url, key)


def approval_rates(supabase: Client, since: date, until: date):
    """Per-agent approval rate for the period, joined via routing_trace."""
    result = supabase.rpc(
        "analyze_feedback_and_recommend",
        {"p_analysis_date": until.isoformat()},
    ).execute()
    return result.data or []


def raw_summary(supabase: Client, since: date, until: date):
    """Fallback direct query when the SQL function returns nothing (low volume)."""
    trace = (
        supabase.table("maestro_routing_trace")
        .select("id, primary_agent, user_approved, timestamp")
        .gte("timestamp", since.isoformat())
        .lte("timestamp", until.isoformat())
        .execute()
    )
    rows = trace.data or []
    by_agent = {}
    for r in rows:
        agent = r["primary_agent"]
        by_agent.setdefault(agent, {"total": 0, "approved": 0})
        by_agent[agent]["total"] += 1
        if r.get("user_approved"):
            by_agent[agent]["approved"] += 1
    return by_agent


def print_report(recommendations, raw, since, until):
    print(f"\nWeekly Feedback Report — {since.isoformat()} to {until.isoformat()}\n")

    print("Approval rates by agent:")
    print(f"{'agent':30} {'total':>6} {'approved':>9} {'rate':>7}")
    for agent, stats in sorted(raw.items(), key=lambda x: -x[1]["total"]):
        rate = (stats["approved"] / stats["total"] * 100) if stats["total"] else 0.0
        print(f"{agent:30} {stats['total']:>6} {stats['approved']:>9} {rate:>6.1f}%")

    print("\nRecommendations (from analyze_feedback_and_recommend):")
    if not recommendations:
        print("  none this week — approval rates within normal range")
    for rec in recommendations:
        print(f"  [{rec['priority']}] {rec['agent_slug']}: {rec['recommendation']} "
              f"(n={rec['affected_feedback_count']})")


def create_github_issues(recommendations, repo: str, dry_run: bool):
    """Create a GitHub issue per HIGH priority recommendation.

    Requires `gh` CLI authenticated in the environment (CI: GH_TOKEN secret).
    """
    import subprocess

    high_priority = [r for r in recommendations if r["priority"] == "HIGH"]
    if not high_priority:
        print("No HIGH priority recommendations — no issues created.")
        return

    for rec in high_priority:
        title = f"[routing] {rec['agent_slug']}: {rec['recommendation'][:80]}"
        body = (
            f"**Agent:** {rec['agent_slug']}\n"
            f"**Priority:** {rec['priority']}\n"
            f"**Affected feedback events:** {rec['affected_feedback_count']}\n\n"
            f"{rec['recommendation']}\n\n"
            f"Generated by `scripts/weekly_feedback_report.py`. "
            f"See `maestro_routing_keywords` for current keyword weights and "
            f"`docs/TRAINING-GUIDE-DEVOPS-DATA-TEAMS.md` Part B §2 for the review workflow."
        )
        if dry_run:
            print(f"[dry-run] Would create issue: {title}")
            continue
        subprocess.run(
            ["gh", "issue", "create", "--repo", repo, "--title", title, "--body", body,
             "--label", "routing-improvement"],
            check=True,
        )
        print(f"Created issue: {title}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", type=str, default=None, help="YYYY-MM-DD, default: 7 days ago")
    parser.add_argument("--until", type=str, default=None, help="YYYY-MM-DD, default: today")
    parser.add_argument("--create-issues", action="store_true",
                        help="Create GitHub issues for HIGH priority recommendations")
    parser.add_argument("--repo", type=str, default="manta/manta-hub",
                        help="owner/repo for --create-issues")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    until = date.fromisoformat(args.until) if args.until else date.today()
    since = date.fromisoformat(args.since) if args.since else until - timedelta(days=7)

    supabase = get_client()
    recommendations = approval_rates(supabase, since, until)
    raw = raw_summary(supabase, since, until)

    print_report(recommendations, raw, since, until)

    if args.create_issues:
        create_github_issues(recommendations, args.repo, args.dry_run)


if __name__ == "__main__":
    main()
