-- Migration: RAG Chunks — Pavimentação (rod:pav:*)
-- Date: 2026-08-04 (Schema real: manta_rag_documents + manta_rag_chunks)
-- Status: Fase II consolidation
-- Source: .claude/knowledge/rodovias/pavimentacao/08-pavimentacao-especializacoes.md
-- Chunks: 20 entries covering 20 specializations

BEGIN TRANSACTION;

-- 1. Create document record
INSERT INTO manta_rag_documents (doc_id, uri, titulo, tipo, projeto, data_indexacao, hash_conteudo, metadados, fonte_origem)
VALUES (
  'rod-pav-especializacoes-20260804',
  'knowledge/rodovias/pavimentacao/08-pavimentacao-especializacoes.md',
  'Pavimentação — 20 Especializações (materiais, projeto, execução, monitoramento, reabilitação)',
  'knowledge_base',
  'rodovias',
  NOW(),
  'workflow-consolidacao-20agentes-1166k-tokens',
  jsonb_build_object(
    'collection_slug', 'rodovias-pavimentacao',
    'prefix_storage', 'rod:pav:',
    'source_type', 'workflow-consolidacao',
    'agents_count', 20,
    'total_tokens_consolidated', 1166000,
    'agent_specializations', jsonb_build_array('materiais', 'agregados', 'reciclagem', 'misturas_especiais', 'concreto_portland', 'aashto_1993', 'mecanistico_empirico', 'fadiga_deformacao', 'modulo_dinamico', 'drenagem', 'compactacao', 'equipamentos', 'sequencia_obra', 'orcamento_integrado', 'gpr_fwd', 'reforco_estrutural', 'recapeamento', 'reabilitacao', 'casos_reais', 'sustentabilidade')
  ),
  'workflow-consolidacao-60agentes'
)
ON CONFLICT (doc_id) DO NOTHING;

-- 2. Insert chunks from 20 specializations
INSERT INTO manta_rag_chunks (doc_id, posicao, texto, tokens, metadados_chunk)
SELECT
  'rod-pav-especializacoes-20260804',
  row_number() OVER (ORDER BY posicao),
  texto,
  tokens,
  metadados_chunk
FROM (
  SELECT 1 as posicao,
    'Ligantes asfálticos — CAP convencional (50/70, 60/80), CAP-modificado com SBS (elasticidade, recuperação), CAP polímero elastomérico (flexibilidade baixa T), CAP borracha (amortecimento, sustentabilidade). Normas: NBR 15086, DNER-ME 001. Viscosidade cinemática especificada. Aplicações: CBUQ convencional (CAP 50/70), drenante (CAP-modificado SBS), porosa (CAP elastomérico).' as texto,
    CEIL(LENGTH('Ligantes asfálticos — CAP convencional (50/70, 60/80), CAP-modificado com SBS (elasticidade, recuperação), CAP polímero elastomérico (flexibilidade baixa T), CAP borracha (amortecimento, sustentabilidade). Normas: NBR 15086, DNER-ME 001. Viscosidade cinemática especificada. Aplicações: CBUQ convencional (CAP 50/70), drenante (CAP-modificado SBS), porosa (CAP elastomérico).') / 4)::int as tokens,
    jsonb_build_object('prefix_storage', 'rod:pav:materiais', 'categoria', 'materiais', 'section', '1', 'subsection', '1.1', 'collection_slug', 'rodovias-pavimentacao') as metadados_chunk
  UNION ALL SELECT 2, 'Agregados para CBUQ — classificação granulométrica: graúdo >4,75mm (brita 1, brita 2), miúdo <4,75mm (areia natural, britagem), filler (pó pedra, cimento, cal). Origem regional Brasil: Região Sul (SP, PR) granito/gnaisse/quartzito (boa qualidade), Sudeste (RJ, MG) itabirito (polido, menor resistência), Nordeste (BA, PE) quartzito/gnaisse (resistente, escassez areia), Centro-Oeste (GO, MS) calcário/arenito (macios). Ensaios: NBR 12896, atrito ≥0,45 (rodovias principais), Los Angeles ≤40%, absorção ≤2%.', CEIL(LENGTH('Agregados para CBUQ — classificação granulométrica: graúdo >4,75mm (brita 1, brita 2), miúdo <4,75mm (areia natural, britagem), filler (pó pedra, cimento, cal). Origem regional Brasil: Região Sul (SP, PR) granito/gnaisse/quartzito (boa qualidade), Sudeste (RJ, MG) itabirito (polido, menor resistência), Nordeste (BA, PE) quartzito/gnaisse (resistente, escassez areia), Centro-Oeste (GO, MS) calcário/arenito (macios). Ensaios: NBR 12896, atrito ≥0,45 (rodovias principais), Los Angeles ≤40%, absorção ≤2%.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:agregados', 'categoria', 'agregados', 'section', '1', 'subsection', '1.2', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 3, 'RAP (Reclaimed Asphalt Pavement) — taxa máxima DNIT 20-30% em massa total (limitado rigidez ligante residual). Compatibilidade: usar CAP-modificado com ligante novo. Processamento: moagem, peneiramento, uniformização granulométrica. Benefício: economia ~50% agregado novo, sustentabilidade. RCD máximo em base/subbase 50% (mais permissivo que CBUQ). Legislação: CONAMA 307/2002, NBR 15116. Casos reais: Concessão Imigrantes (SP) 25% RAP (economia R$ 2.3M/100km), Rodovia Açúcar (SP) 15% RAP + 10% RCD.', CEIL(LENGTH('RAP (Reclaimed Asphalt Pavement) — taxa máxima DNIT 20-30% em massa total (limitado rigidez ligante residual). Compatibilidade: usar CAP-modificado com ligante novo. Processamento: moagem, peneiramento, uniformização granulométrica. Benefício: economia ~50% agregado novo, sustentabilidade. RCD máximo em base/subbase 50% (mais permissivo que CBUQ). Legislação: CONAMA 307/2002, NBR 15116. Casos reais: Concessão Imigrantes (SP) 25% RAP (economia R$ 2.3M/100km), Rodovia Açúcar (SP) 15% RAP + 10% RCD.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:reciclagem', 'categoria', 'reciclagem', 'section', '1', 'subsection', '1.3', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 4, 'CBUQ Porosa (Drenante) — vazios ≥16-18% (vs 4-8% convencional), reduz ruído, melhor drenagem, menor aquaplanagem. Limitações: vida útil 6-10 anos, manutenção anual (limpeza jato). Custo +30-40%. SMA (Stone Mastic Asphalt) — esqueleto agregado graúdo + matriz filler/ligante, resistência deformação, 15-20 anos, boa drenagem. Custo +40-60%. Aplicação: tráfego pesado, clima quente T>40°C. Norma DNER-ES 385/99. Semi-abertas: vazios 8-12%, balanço drenagem/durabilidade.', CEIL(LENGTH('CBUQ Porosa (Drenante) — vazios ≥16-18% (vs 4-8% convencional), reduz ruído, melhor drenagem, menor aquaplanagem. Limitações: vida útil 6-10 anos, manutenção anual (limpeza jato). Custo +30-40%. SMA (Stone Mastic Asphalt) — esqueleto agregado graúdo + matriz filler/ligante, resistência deformação, 15-20 anos, boa drenagem. Custo +40-60%. Aplicação: tráfego pesado, clima quente T>40°C. Norma DNER-ES 385/99. Semi-abertas: vazios 8-12%, balanço drenagem/durabilidade.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:misturas_especiais', 'categoria', 'misturas_especiais', 'section', '1', 'subsection', '1.4', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 5, 'CCP (Concreto Portland em Rodovia) — tipos CPACC (simples), CCP (armado), CPCCR (continuamente armado). Rígido vs flexível: CCP mais durável 30+ anos, menor manutenção, custo inicial +30-40%. Aplicação: tráfego pesado, clima extremo. Especificação: NBR 5732 (cimento), DNIT 010/2004 (projeto). Resistência à compressão ≥35 MPa. Junta 3-6 m. Comparação CBUQ: CBUQ mais rápida construção, CCP maior durabilidade total.', CEIL(LENGTH('CCP (Concreto Portland em Rodovia) — tipos CPACC (simples), CCP (armado), CPCCR (continuamente armado). Rígido vs flexível: CCP mais durável 30+ anos, menor manutenção, custo inicial +30-40%. Aplicação: tráfego pesado, clima extremo. Especificação: NBR 5732 (cimento), DNIT 010/2004 (projeto). Resistência à compressão ≥35 MPa. Junta 3-6 m. Comparação CBUQ: CBUQ mais rápida construção, CCP maior durabilidade total.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:concreto_portland', 'categoria', 'concreto_portland', 'section', '2', 'subsection', '2.1', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 6, 'Método AASHTO 1993 — Equação fundamental: log₁₀(N) = 9.36×log₁₀(SN+1) - 0.20 + [log₁₀(ΔPSI/(4.2-1.5))] / [0.40 + (1094/(SN+1)^5.19)] + 0.372×(EBC-3). Parâmetros: N (repetições eixo 80kN), SN (número estrutural polegadas), ΔPSI (perda serventia, 2-3 típico), EBC (módulo resiliente subrasante psi). Cálculo N: N = AAD × 365 × [(1+i)^A-1] / i × FC × FD. Módulo resiliente: MR(psi) = 2555×CBR^0.64 (CBR<10%), MR = 1043×CBR + 3245 (10-30%). Exemplo: CBR 8% → MR 21.000 psi ≈ 145 MPa.', CEIL(LENGTH('Método AASHTO 1993 — Equação fundamental: log₁₀(N) = 9.36×log₁₀(SN+1) - 0.20 + [log₁₀(ΔPSI/(4.2-1.5))] / [0.40 + (1094/(SN+1)^5.19)] + 0.372×(EBC-3). Parâmetros: N (repetições eixo 80kN), SN (número estrutural polegadas), ΔPSI (perda serventia, 2-3 típico), EBC (módulo resiliente subrasante psi). Cálculo N: N = AAD × 365 × [(1+i)^A-1] / i × FC × FD. Módulo resiliente: MR(psi) = 2555×CBR^0.64 (CBR<10%), MR = 1043×CBR + 3245 (10-30%). Exemplo: CBR 8% → MR 21.000 psi ≈ 145 MPa.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:aashto_1993', 'categoria', 'aashto_1993', 'section', '2', 'subsection', '2.2', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 7, 'Método M-E (Mecanístico-Empírico) — modelagem mecanicista FEM/linear elástica multicamadas, resposta estrutural deformações críticas tração base/compressão subleito, modelos desempenho fadiga/afundamento, variabilidade climática temperatura/umidade/simulação climática, previsão desempenho trincas/afundamento/serviço. Software: PavementME (AASHTO 2008), Everstress, Everpave. Deformações críticas: ε_t (tração base) e σ_v (compressão subleito). Vantagem: maior precisão vs AASHTO 1993, considera clima regional. Desvantagem: complexidade, dados detalhados material (E*, temperatura-dependência), capacitação software.', CEIL(LENGTH('Método M-E (Mecanístico-Empírico) — modelagem mecanicista FEM/linear elástica multicamadas, resposta estrutural deformações críticas tração base/compressão subleito, modelos desempenho fadiga/afundamento, variabilidade climática temperatura/umidade/simulação climática, previsão desempenho trincas/afundamento/serviço. Software: PavementME (AASHTO 2008), Everstress, Everpave. Deformações críticas: ε_t (tração base) e σ_v (compressão subleito). Vantagem: maior precisão vs AASHTO 1993, considera clima regional. Desvantagem: complexidade, dados detalhados material (E*, temperatura-dependência), capacitação software.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:mecanistico_empirico', 'categoria', 'mecanistico_empirico', 'section', '2', 'subsection', '2.3', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 8, 'Fadiga concreto asfáltico — modelo exponencial: N_f = K₁ × (1/ε_t)^K₂. N_f (repetições falha), ε_t (deformação tração), K₁, K₂ constantes material (K₂=3-4). Limite prático: 50-100 repetições pico antes trinca visível. Deformação permanente (afundamento) — mecanismo acúmulo deformação sob repetições carga. Afundamento = Σ(ε_p) × espessura camada. Critério falha DNIT: afundamento máximo ≤20mm em 10 anos. AASHTO M-E: previsão contínua vida útil. Sensibilidade: temperatura +10°C reduz módulo ~30%, afeta vida útil significativamente.', CEIL(LENGTH('Fadiga concreto asfáltico — modelo exponencial: N_f = K₁ × (1/ε_t)^K₂. N_f (repetições falha), ε_t (deformação tração), K₁, K₂ constantes material (K₂=3-4). Limite prático: 50-100 repetições pico antes trinca visível. Deformação permanente (afundamento) — mecanismo acúmulo deformação sob repetições carga. Afundamento = Σ(ε_p) × espessura camada. Critério falha DNIT: afundamento máximo ≤20mm em 10 anos. AASHTO M-E: previsão contínua vida útil. Sensibilidade: temperatura +10°C reduz módulo ~30%, afeta vida útil significativamente.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:fadiga_deformacao', 'categoria', 'fadiga_deformacao', 'section', '2', 'subsection', '2.4', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 9, 'Módulo Dinâmico E* (Complex Modulus) — dependência temperatura e frequência: E* = f(T, ω). Ensaio IDT (Indirect Tensile Test): temperatura -10°C a +60°C (cobrindo Brasil), frequência 0.1-25 Hz (velocidades 5-100 km/h). Resultado: diagrama Cole-Cole, E* e ângulo fase δ. Aplicação: entrada método M-E, sensibilidade climática. Comportamento viscoelástico: E* reduz com T elevada e frequência baixa. Normas: AASHTO TP62 (E* dinâmico), AASHTO TP63 (creep dinâmico). Exemplo: CBUQ em T=40°C apresenta E* ~30% menor que T=20°C.', CEIL(LENGTH('Módulo Dinâmico E* (Complex Modulus) — dependência temperatura e frequência: E* = f(T, ω). Ensaio IDT (Indirect Tensile Test): temperatura -10°C a +60°C (cobrindo Brasil), frequência 0.1-25 Hz (velocidades 5-100 km/h). Resultado: diagrama Cole-Cole, E* e ângulo fase δ. Aplicação: entrada método M-E, sensibilidade climática. Comportamento viscoelástico: E* reduz com T elevada e frequência baixa. Normas: AASHTO TP62 (E* dinâmico), AASHTO TP63 (creep dinâmico). Exemplo: CBUQ em T=40°C apresenta E* ~30% menor que T=20°C.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:modulo_dinamico', 'categoria', 'modulo_dinamico', 'section', '2', 'subsection', '2.5', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 10, 'Drenagem pavimento — base permeável: BGS alta permeabilidade (k ≥10^-2 cm/s). Filtro geotêxtil entre CBUQ e base (retenção/drenagem balanceada). Dreno longitudinal PEAD corrugado perfurado (diâmetro 100-150mm). Impacto vida útil: com drenagem eficiente +30-40%, sem drenagem acúmulo água reduz módulo falha precoce. Manutenção: limpeza anual drenos (risco obstrução silte). Especificação: DNIT 108/2009. Vazão dreno: Q = k × A × i onde i=declividade longitudinal (~2-4%). Posicionamento: sob linha de maior saturação em base.', CEIL(LENGTH('Drenagem pavimento — base permeável: BGS alta permeabilidade (k ≥10^-2 cm/s). Filtro geotêxtil entre CBUQ e base (retenção/drenagem balanceada). Dreno longitudinal PEAD corrugado perfurado (diâmetro 100-150mm). Impacto vida útil: com drenagem eficiente +30-40%, sem drenagem acúmulo água reduz módulo falha precoce. Manutenção: limpeza anual drenos (risco obstrução silte). Especificação: DNIT 108/2009. Vazão dreno: Q = k × A × i onde i=declividade longitudinal (~2-4%). Posicionamento: sob linha de maior saturação em base.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:drenagem', 'categoria', 'drenagem', 'section', '2', 'subsection', '2.5', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 11, 'Grau Compactação GC% = (ρ_campo / ρ_dmáx) × 100%. Especificações DNIT: capa asfáltica GC ≥97% Proctor, base GC ≥95%, subbase GC ≥93%. Equipamento: densímetro nuclear (readout rápido, ±0.5%), menos invasivo. Amostragem: mínimo 3 pontos/100m² pavimento. Impacto: GC<93% compactação inadequada, afundamento precoce, maior permeabilidade; GC≥97% compactação ótima, vida útil máxima. Curva Proctor: determina ω_ótima (teor água ótimo) e ρ_dmáx (densidade máxima). Execução: lançamento em camadas ≤10cm, cada camada 4-6 passadas rolo vibrante.', CEIL(LENGTH('Grau Compactação GC% = (ρ_campo / ρ_dmáx) × 100%. Especificações DNIT: capa asfáltica GC ≥97% Proctor, base GC ≥95%, subbase GC ≥93%. Equipamento: densímetro nuclear (readout rápido, ±0.5%), menos invasivo. Amostragem: mínimo 3 pontos/100m² pavimento. Impacto: GC<93% compactação inadequada, afundamento precoce, maior permeabilidade; GC≥97% compactação ótima, vida útil máxima. Curva Proctor: determina ω_ótima (teor água ótimo) e ρ_dmáx (densidade máxima). Execução: lançamento em camadas ≤10cm, cada camada 4-6 passadas rolo vibrante.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:compactacao', 'categoria', 'compactacao', 'section', '3', 'subsection', '3.1', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 12, 'Motoniveladoras — modelo CAT 140 (padrão), Volvo GG140 (premium). Produção 200-400 m²/h (espalhamento+nivelação). Custo horário SICRO 2024: R$ 350-450/h. Rolos compactadores — rolo liso (vibrante) 80-130kN (agregados, base), rolo pneumático 100-200kN (uniformidade, acabamento). Sequência: rolo liso (núcleo) + rolo pneumático (finalização). Produção típica motoniveladoras + rolos: 300-400 m²/h em 10cm espessura. Equipamentos adicionais: vibrador de pista, varredor mecânico, imprimadora (ligante). Manutenção: filtro óleo, pneus, correntes.', CEIL(LENGTH('Motoniveladoras — modelo CAT 140 (padrão), Volvo GG140 (premium). Produção 200-400 m²/h (espalhamento+nivelação). Custo horário SICRO 2024: R$ 350-450/h. Rolos compactadores — rolo liso (vibrante) 80-130kN (agregados, base), rolo pneumático 100-200kN (uniformidade, acabamento). Sequência: rolo liso (núcleo) + rolo pneumático (finalização). Produção típica motoniveladoras + rolos: 300-400 m²/h em 10cm espessura. Equipamentos adicionais: vibrador de pista, varredor mecânico, imprimadora (ligante). Manutenção: filtro óleo, pneus, correntes.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:equipamentos', 'categoria', 'equipamentos', 'section', '3', 'subsection', '3.2', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 13, 'Cronograma típico 100km pavimentação CBUQ: (1) preparo subrasante 10 dias (limpeza, escarificação); (2) imprimação/selagem 3 dias; (3) base 15 dias (espalhamento, compactação, cura); (4) capa asfáltica 20 dias (usinagem, transporte, lançamento, compactação); (5) acabamento+acessórios 10 dias. Total ~58 dias (8-10 semanas). Custos SICRO 2024 por m² CBUQ 5cm: material asfáltico R$ 85-110, m.o. R$ 35-50, equipamento R$ 25-40, total R$ 145-200 (varia região). Frentes paralelas possível para aceleração; risco compactação inadequada se frentes próximas.', CEIL(LENGTH('Cronograma típico 100km pavimentação CBUQ: (1) preparo subrasante 10 dias (limpeza, escarificação); (2) imprimação/selagem 3 dias; (3) base 15 dias (espalhamento, compactação, cura); (4) capa asfáltica 20 dias (usinagem, transporte, lançamento, compactação); (5) acabamento+acessórios 10 dias. Total ~58 dias (8-10 semanas). Custos SICRO 2024 por m² CBUQ 5cm: material asfáltico R$ 85-110, m.o. R$ 35-50, equipamento R$ 25-40, total R$ 145-200 (varia região). Frentes paralelas possível para aceleração; risco compactação inadequada se frentes próximas.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:sequencia_obra', 'categoria', 'sequencia_obra', 'section', '3', 'subsection', '3.3', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 14, 'Orçamento SICRO 2024 — BDI (Benefício, Despesa, Impostos) típico 30-40%. Composição custo: (1) material asfáltico 40-45%, (2) agregados 20-25%, (3) mão-obra 15-20%, (4) equipamento 10-15%, (5) impostos 10-15%. Custos variáveis região: agregados mais caros NE (transporte longas distâncias), ligante flutuante (óleo Brent), m.o. maior SP-RJ. Contingência: +10-15% imprevistos (chuva, retrabalho, imprevisto). Análise custo-benefício: CBUQ convencional vs SMA vs CCP. Licitação: composição SICRO obrigatória DNIT, permitido desvios <10% justificado.', CEIL(LENGTH('Orçamento SICRO 2024 — BDI (Benefício, Despesa, Impostos) típico 30-40%. Composição custo: (1) material asfáltico 40-45%, (2) agregados 20-25%, (3) mão-obra 15-20%, (4) equipamento 10-15%, (5) impostos 10-15%. Custos variáveis região: agregados mais caros NE (transporte longas distâncias), ligante flutuante (óleo Brent), m.o. maior SP-RJ. Contingência: +10-15% imprevistos (chuva, retrabalho, imprevisto). Análise custo-benefício: CBUQ convencional vs SMA vs CCP. Licitação: composição SICRO obrigatória DNIT, permitido desvios <10% justificado.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:orcamento_integrado', 'categoria', 'orcamento_integrado', 'section', '3', 'subsection', '3.4', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 15, 'GPR (Ground Penetrating Radar) — mapeamento camadas, detecção vazios, delaminação. Penetração 0.5-2m (depende estrutura), resolução ±2-3cm (condições ideais). Custo R$ 3.000-5.000/km (portátil). FWD (Falling Weight Deflectometer) — deflexão estrutural sob carga dinâmica (50-300kN), bacia deflexão, módulo retroanalisado. Custo R$ 5.000-10.000/km (laboratório móvel). Integração GPR+FWD: diagnóstico estrutural + material completo. Acesso contínuo pavimento via pontos FWD cada 100-200m, GPR contínuo. Interpretação retroanálise FEM para estimar módulos camadas existentes (base, subbase, subleito).', CEIL(LENGTH('GPR (Ground Penetrating Radar) — mapeamento camadas, detecção vazios, delaminação. Penetração 0.5-2m (depende estrutura), resolução ±2-3cm (condições ideais). Custo R$ 3.000-5.000/km (portátil). FWD (Falling Weight Deflectometer) — deflexão estrutural sob carga dinâmica (50-300kN), bacia deflexão, módulo retroanalisado. Custo R$ 5.000-10.000/km (laboratório móvel). Integração GPR+FWD: diagnóstico estrutural + material completo. Acesso contínuo pavimento via pontos FWD cada 100-200m, GPR contínuo. Interpretação retroanálise FEM para estimar módulos camadas existentes (base, subbase, subleito).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:gpr_fwd', 'categoria', 'gpr_fwd', 'section', '4', 'subsection', '4.1', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 16, 'Reforço estrutural — decisão reforço vs recapeamento: ICP>60 afundamento<10mm = recapeamento (CBUQ 3-4cm); ICP 40-60 afundamento 10-20mm = reforço (CBUQ 4-6cm); ICP<40 ou afundamento>20mm = reabilitação. Dimensionamento: SN_requerido_novo = SN_estrutural_atual + SN_incremental (calculado AASHTO ou M-E). Compatibilidade material: CAP-modificado sobre CBUQ convencional → melhor aderência. Fresagem 2-3cm (remoção camada oxidada) recomendada. Caso BR-116 (RJ) 2019: reforço CBUQ 6cm → extensão vida +8 anos, custo R$ 25M/100km.', CEIL(LENGTH('Reforço estrutural — decisão reforço vs recapeamento: ICP>60 afundamento<10mm = recapeamento (CBUQ 3-4cm); ICP 40-60 afundamento 10-20mm = reforço (CBUQ 4-6cm); ICP<40 ou afundamento>20mm = reabilitação. Dimensionamento: SN_requerido_novo = SN_estrutural_atual + SN_incremental (calculado AASHTO ou M-E). Compatibilidade material: CAP-modificado sobre CBUQ convencional → melhor aderência. Fresagem 2-3cm (remoção camada oxidada) recomendada. Caso BR-116 (RJ) 2019: reforço CBUQ 6cm → extensão vida +8 anos, custo R$ 25M/100km.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:reforco_estrutural', 'categoria', 'reforco_estrutural', 'section', '4', 'subsection', '4.2', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 17, 'Recapeamento sobreposição — espessura típica 3-5cm CBUQ, in situ sem demolição, economia ~40% vs reabilitação, rapidez execução. Limitação: não resolve problemas estruturais profundos. Vida útil estendida +10-15 anos (se base intacta). Recapeamento com fresagem parcial (2-3cm) — remove camada oxidada/danificada, melhora aderência, custo +20-30%. Aplicação: ICP 55-70 + afundamento<15mm = simples; ICP 40-55 + afundamento 15-25mm = com fresagem. Risco: superfície recapeada desgrudar se interface suja/óleo. Preparação: limpeza jato, tack coat (ligante adesivo). Prazo: 2-3 semanas por 100km (vs 8-10 reabilitação).', CEIL(LENGTH('Recapeamento sobreposição — espessura típica 3-5cm CBUQ, in situ sem demolição, economia ~40% vs reabilitação, rapidez execução. Limitação: não resolve problemas estruturais profundos. Vida útil estendida +10-15 anos (se base intacta). Recapeamento com fresagem parcial (2-3cm) — remove camada oxidada/danificada, melhora aderência, custo +20-30%. Aplicação: ICP 55-70 + afundamento<15mm = simples; ICP 40-55 + afundamento 15-25mm = com fresagem. Risco: superfície recapeada desgrudar se interface suja/óleo. Preparação: limpeza jato, tack coat (ligante adesivo). Prazo: 2-3 semanas por 100km (vs 8-10 reabilitação).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:recapeamento', 'categoria', 'recapeamento', 'section', '4', 'subsection', '4.3', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 18, 'Reabilitação completa — sequência: (1) demolição/remoção pavimento (fresar até 20+cm); (2) preparo subrasante/base (escavação adicional se necessário); (3) reconstrução camadas (base, capa); (4) acabamento+acessórios. Duração 2-3x maior que pavimentação nova, custo 1.5x-2x convencional. Indicação: ICP<40, afundamento>20mm, trincas alligator severas, falhas estruturais profundas. Caso BR-101 (BA) 2018: reabilitação 50km → custo R$ 45M, prazo 18 meses, base cimentada (BCS) nova. Benefício: vida projeto 20 anos garantida, maior acessibilidade futura.', CEIL(LENGTH('Reabilitação completa — sequência: (1) demolição/remoção pavimento (fresar até 20+cm); (2) preparo subrasante/base (escavação adicional se necessário); (3) reconstrução camadas (base, capa); (4) acabamento+acessórios. Duração 2-3x maior que pavimentação nova, custo 1.5x-2x convencional. Indicação: ICP<40, afundamento>20mm, trincas alligator severas, falhas estruturais profundas. Caso BR-101 (BA) 2018: reabilitação 50km → custo R$ 45M, prazo 18 meses, base cimentada (BCS) nova. Benefício: vida projeto 20 anos garantida, maior acessibilidade futura.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:reabilitacao', 'categoria', 'reabilitacao', 'section', '4', 'subsection', '4.4', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 19, 'Casos reais O&M Brasil — BR-116 RJ 2019: localização km 180-280 Paraíba do Sul, ICP 65, afundamento 8mm, trincas transversais, intervenção reforço CBUQ 6cm + fresagem 2cm, resultado ICP→82 em 5 anos, vida útil +10 anos, custo R$ 25M/100km. BR-101 BA 2018: Ilhéus-Itabuna, pavimento 1995 (23 anos), afundamento>25mm, estrutura colapsada, solução reabilitação total base BCS, resultado nova pavimentação projeto 20 anos, custo R$ 350/m², prazo 16 meses. Concessão Imigrantes SP: 25% RAP recapeamento, economia R$ 2.3M/100km. Rodovia Açúcar SP: 15% RAP + 10% RCD base, sustentabilidade certificada.', CEIL(LENGTH('Casos reais O&M Brasil — BR-116 RJ 2019: localização km 180-280 Paraíba do Sul, ICP 65, afundamento 8mm, trincas transversais, intervenção reforço CBUQ 6cm + fresagem 2cm, resultado ICP→82 em 5 anos, vida útil +10 anos, custo R$ 25M/100km. BR-101 BA 2018: Ilhéus-Itabuna, pavimento 1995 (23 anos), afundamento>25mm, estrutura colapsada, solução reabilitação total base BCS, resultado nova pavimentação projeto 20 anos, custo R$ 350/m², prazo 16 meses. Concessão Imigrantes SP: 25% RAP recapeamento, economia R$ 2.3M/100km. Rodovia Açúcar SP: 15% RAP + 10% RCD base, sustentabilidade certificada.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:casos_reais', 'categoria', 'casos_reais', 'section', '4', 'subsection', '4.5', 'collection_slug', 'rodovias-pavimentacao')
  UNION ALL SELECT 20, 'Sustentabilidade e redução de CO₂ — CBUQ convencional 350-400kg CO₂/m² (ciclo completo); CBUQ 20% RAP -10% CO₂; asfalto quente-morno (100°C vs 160°C) -15-20%; asfalto borracha (RAP+pneus) -25-30%. Materiais bio-alternativos: ligante bio-asfalto (óleo vegetal) 50% redução CO₂ (limitado adoção Brasil), agregados reciclados 30% redução impacto ambiental. Certificações: BREEAM pavimentação, rating sustentabilidade FGV. Estudo ACV (Análise Ciclo Vida) padrão ISO 14040-14044. Recomendação: usar RAP máximo compatível (20-30%), considerar asfalto quente-morno para grandes volumes, especificar agregados reciclados em base quando disponível.', CEIL(LENGTH('Sustentabilidade e redução de CO₂ — CBUQ convencional 350-400kg CO₂/m² (ciclo completo); CBUQ 20% RAP -10% CO₂; asfalto quente-morno (100°C vs 160°C) -15-20%; asfalto borracha (RAP+pneus) -25-30%. Materiais bio-alternativos: ligante bio-asfalto (óleo vegetal) 50% redução CO₂ (limitado adoção Brasil), agregados reciclados 30% redução impacto ambiental. Certificações: BREEAM pavimentação, rating sustentabilidade FGV. Estudo ACV (Análise Ciclo Vida) padrão ISO 14040-14044. Recomendação: usar RAP máximo compatível (20-30%), considerar asfalto quente-morno para grandes volumes, especificar agregados reciclados em base quando disponível.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:pav:sustentabilidade', 'categoria', 'sustentabilidade', 'section', '4', 'subsection', '4.6', 'collection_slug', 'rodovias-pavimentacao')
) chunks;

COMMIT;

-- Verification
SELECT
  COUNT(*) as total_chunks,
  COUNT(DISTINCT metadados_chunk->>'prefix_storage') as distinct_prefixes,
  (SELECT COUNT(*) FROM manta_rag_documents WHERE doc_id = 'rod-pav-especializacoes-20260804') as documents_created
FROM manta_rag_chunks
WHERE doc_id = 'rod-pav-especializacoes-20260804';
