-- Migration: RAG Chunks — O&M (rod:om:*)
-- Date: 2026-08-04 (Schema real: manta_rag_documents + manta_rag_chunks)
-- Status: Fase II consolidation
-- Source: .claude/knowledge/rodovias/om/11-om-especializacoes.md
-- Chunks: 10 entries covering 10 specializations

BEGIN TRANSACTION;

-- 1. Create document record
INSERT INTO manta_rag_documents (doc_id, uri, titulo, tipo, projeto, data_indexacao, hash_conteudo, metadados, fonte_origem)
VALUES (
  'rod-om-especializacoes-20260804',
  'knowledge/rodovias/om/11-om-especializacoes.md',
  'O&M (Operação & Manutenção) — 10 Especializações (inspeção, monitoramento, manutenção, reabilitação)',
  'knowledge_base',
  'rodovias',
  NOW(),
  'workflow-consolidacao-10agentes-745k-tokens',
  jsonb_build_object(
    'collection_slug', 'rodovias-om',
    'prefix_storage', 'rod:om:',
    'source_type', 'workflow-consolidacao',
    'agents_count', 10,
    'total_tokens_consolidated', 745000,
    'agent_specializations', jsonb_build_array('inspeção_estrutural', 'avaliacao_condicao', 'monitoramento_trafego', 'qualidade_agua_conama', 'previsao_deterioracao', 'reparos_localizados', 'reabilitacao_drenagem', 'analise_lcc', 'extensao_vida_util', 'tecnologias_avancadas')
  ),
  'workflow-consolidacao-60agentes'
)
ON CONFLICT (doc_id) DO NOTHING;

-- 2. Insert chunks from 10 specializations
INSERT INTO manta_rag_chunks (doc_id, posicao, texto, tokens, metadados_chunk)
SELECT
  'rod-om-especializacoes-20260804',
  row_number() OVER (ORDER BY posicao),
  texto,
  tokens,
  metadados_chunk
FROM (
  SELECT 1 as posicao,
    'Inspeção estrutural (auscultação) — avaliação condição pavimento, drenagem, taludes. Técnicas: visual (lesões superficiais fotografadas), GPS RTK (geoposicionamento precisão ±2cm), GPR (mapeamento camadas profundas), FWD (deflexão estrutural). Formulários DNIT: checklist lesões (trincas, afundamento, panelas, lama), severidade escala 1-5. Frequência: anual (rodovia operação normal), bianual (rodovia critica tráfego pesado), pós-evento (chuva 100-ano, acidente). Custo inspeção: R$ 2.000-3.000/100km (visual + GPS); +R$ 5.000-8.000 se GPR/FWD incluído. Documentação: relatório fotográfico, planta lesões geoposicionadas, conclusões condição estrutural. Norma DNIT 719/2006, NBR 6118 (estrutura).' as texto,
    CEIL(LENGTH('Inspeção estrutural (auscultação) — avaliação condição pavimento, drenagem, taludes. Técnicas: visual (lesões superficiais fotografadas), GPS RTK (geoposicionamento precisão ±2cm), GPR (mapeamento camadas profundas), FWD (deflexão estrutural). Formulários DNIT: checklist lesões (trincas, afundamento, panelas, lama), severidade escala 1-5. Frequência: anual (rodovia operação normal), bianual (rodovia critica tráfego pesado), pós-evento (chuva 100-ano, acidente). Custo inspeção: R$ 2.000-3.000/100km (visual + GPS); +R$ 5.000-8.000 se GPR/FWD incluído. Documentação: relatório fotográfico, planta lesões geoposicionadas, conclusões condição estrutural. Norma DNIT 719/2006, NBR 6118 (estrutura).') / 4)::int as tokens,
    jsonb_build_object('prefix_storage', 'rod:om:inspeção_estrutural', 'categoria', 'inspeção_estrutural', 'section', '1', 'subsection', '1.1', 'collection_slug', 'rodovias-om') as metadados_chunk
  UNION ALL SELECT 2, 'Avaliação PCI/ICP — índices condição pavimento internacionais vs Brasil. PCI (Pavement Condition Index) 0-100 (100=novo, 0=falha), baseado ASTM D6433 (tipo/severidade lesão). ICP (Índice de Condição Pavimento) DNIT 0-100 (escala invertida: 100=ótimo, 0=péssimo), derivado PCI mas ajustado experiência Brasil. Método: divisão seção regular (idealmente 500m), amostragem lesões (método estacionário 100m²), cálculo índice fórmula, mapa isoietas condição. Exemplo BR-116 RJ km 127: ICP 57.6 (regular, intervenção recomendada em 2-3 anos). Sensibilidade: ICP afundamento <5mm não penaliza, >10mm reduz ICP ~20 pontos. Correlação vida útil: ICP 70+ (12-18 anos restante), ICP 40-70 (5-12 anos), ICP <40 (0-5 anos). Norma DNIT 010/2003-PRO, ASTM D6433.', CEIL(LENGTH('Avaliação PCI/ICP — índices condição pavimento internacionais vs Brasil. PCI (Pavement Condition Index) 0-100 (100=novo, 0=falha), baseado ASTM D6433 (tipo/severidade lesão). ICP (Índice de Condição Pavimento) DNIT 0-100 (escala invertida: 100=ótimo, 0=péssimo), derivado PCI mas ajustado experiência Brasil. Método: divisão seção regular (idealmente 500m), amostragem lesões (método estacionário 100m²), cálculo índice fórmula, mapa isoietas condição. Exemplo BR-116 RJ km 127: ICP 57.6 (regular, intervenção recomendada em 2-3 anos). Sensibilidade: ICP afundamento <5mm não penaliza, >10mm reduz ICP ~20 pontos. Correlação vida útil: ICP 70+ (12-18 anos restante), ICP 40-70 (5-12 anos), ICP <40 (0-5 anos). Norma DNIT 010/2003-PRO, ASTM D6433.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:avaliacao_condicao', 'categoria', 'avaliacao_condicao', 'section', '1', 'subsection', '1.2', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 3, 'Monitoramento tráfego (VDM) — contagem veículos, composição (leves/pesados), crescimento. Equipamento: tubo pneumático (contar eixos, detectar sentido, categoria), contador automático (sensor infravermelho, registra 24h). Procedimento: 7 dias contagem contínua (representam semana típica), expansão para AADT (volume diário anual médio), aplicar fator sazonal (mês, estação). Análise: VDM histórico (5-10 anos) → crescimento anual (regressão linear), previsão futuro (período projeto 20 anos). Exemplo BR-116 km 450: VDM 1.063 veículos/dia, composição 70% leves + 30% pesados, crescimento 4.7% a.a. (período 10 anos anterior). Impacto: crescimento >3% requer intervenção antes previsto (pavimento dimensionado N inferior). Custo monitoramento: R$ 3.000-5.000/ponto (7 dias tubo pneumático). Norma DNIT IPR 732, AASHTO procedimento.', CEIL(LENGTH('Monitoramento tráfego (VDM) — contagem veículos, composição (leves/pesados), crescimento. Equipamento: tubo pneumático (contar eixos, detectar sentido, categoria), contador automático (sensor infravermelho, registra 24h). Procedimento: 7 dias contagem contínua (representam semana típica), expansão para AADT (volume diário anual médio), aplicar fator sazonal (mês, estação). Análise: VDM histórico (5-10 anos) → crescimento anual (regressão linear), previsão futuro (período projeto 20 anos). Exemplo BR-116 km 450: VDM 1.063 veículos/dia, composição 70% leves + 30% pesados, crescimento 4.7% a.a. (período 10 anos anterior). Impacto: crescimento >3% requer intervenção antes previsto (pavimento dimensionado N inferior). Custo monitoramento: R$ 3.000-5.000/ponto (7 dias tubo pneumático). Norma DNIT IPR 732, AASHTO procedimento.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:monitoramento_trafego', 'categoria', 'monitoramento_trafego', 'section', '1', 'subsection', '1.3', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 4, 'Qualidade água drenagem (CONAMA) — monitoramento efluente rodovia quanto SST (sedimento), turbidez, óleos, DBO₅. Limites CONAMA 357/430 classe 2: SST ≤100 mg/L, turbidez ≤40 UNT, óleos ≤0.3 mg/L, DBO₅ ≤5 mg/L. Amostragem: 3 eventos chuva/ano, coleta entrada/saída drenagem, preservação amostra (frigorífico 4°C, entrega <24h laboratório). Análise: laboratório certificado ABNT ISO 17025 (credibilidade jurídica). Exemplo BR-116 km 420-422 SP: SST 320 mg/L em chuva (vs 100 limite CONAMA) → não conformidade → bacia sedimentação instalada (reduz 150 mg/L). Custo monitoramento: R$ 3.000-8.000/ano (amostragem + análise completa 4 parâmetros). Legislação: CONAMA 357, lei estadual (SP Lei 997/76 ainda mais restritiva), RIMA cláusula O&M. Responsabilidade: concedente/empreiteira até 5 anos pós-obra (ou contrato estendido).', CEIL(LENGTH('Qualidade água drenagem (CONAMA) — monitoramento efluente rodovia quanto SST (sedimento), turbidez, óleos, DBO₅. Limites CONAMA 357/430 classe 2: SST ≤100 mg/L, turbidez ≤40 UNT, óleos ≤0.3 mg/L, DBO₅ ≤5 mg/L. Amostragem: 3 eventos chuva/ano, coleta entrada/saída drenagem, preservação amostra (frigorífico 4°C, entrega <24h laboratório). Análise: laboratório certificado ABNT ISO 17025 (credibilidade jurídica). Exemplo BR-116 km 420-422 SP: SST 320 mg/L em chuva (vs 100 limite CONAMA) → não conformidade → bacia sedimentação instalada (reduz 150 mg/L). Custo monitoramento: R$ 3.000-8.000/ano (amostragem + análise completa 4 parâmetros). Legislação: CONAMA 357, lei estadual (SP Lei 997/76 ainda mais restritiva), RIMA cláusula O&M. Responsabilidade: concedente/empreiteira até 5 anos pós-obra (ou contrato estendido).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:qualidade_agua_conama', 'categoria', 'qualidade_agua_conama', 'section', '1', 'subsection', '1.4', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 5, 'Previsão deterioração (curva S) — modelo ICP vs tempo baseado HDM-4 AASHTO. Comportamento típico: ICP 100 (novo) → redução lenta primeiros 2-3 anos (100→85, weathering), depois redução acelerada (85→50 em 7-10 anos, fadiga estrutural), colapso rápido (50→30 em 2-3 anos, falhas generalizadas). Fatores climáticos: T elevada (asfalto amolece), umidade (base satada, reduz módulo), tráfego pesado (aceleração colapso). Projeção BR-116: ICP 78 (2020) sem intervenção → ICP 28 (2035), 15 anos redução 50 pontos (reabilitação necessária 2025-2030). Sensibilidade: +1% crescimento tráfego → redução vida 2-3 anos; inadequada drenagem → redução vida 40%; reforço +6cm → extensão vida 8-12 anos. Norma DNIT 006/2003, HDM-4 modelo, PavementME software. Validação: comparar projeção vs observado realizado (modelo ajusta com tempo).', CEIL(LENGTH('Previsão deterioração (curva S) — modelo ICP vs tempo baseado HDM-4 AASHTO. Comportamento típico: ICP 100 (novo) → redução lenta primeiros 2-3 anos (100→85, weathering), depois redução acelerada (85→50 em 7-10 anos, fadiga estrutural), colapso rápido (50→30 em 2-3 anos, falhas generalizadas). Fatores climáticos: T elevada (asfalto amolece), umidade (base satada, reduz módulo), tráfego pesado (aceleração colapso). Projeção BR-116: ICP 78 (2020) sem intervenção → ICP 28 (2035), 15 anos redução 50 pontos (reabilitação necessária 2025-2030). Sensibilidade: +1% crescimento tráfego → redução vida 2-3 anos; inadequada drenagem → redução vida 40%; reforço +6cm → extensão vida 8-12 anos. Norma DNIT 006/2003, HDM-4 modelo, PavementME software. Validação: comparar projeção vs observado realizado (modelo ajusta com tempo).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:previsao_deterioracao', 'categoria', 'previsao_deterioracao', 'section', '2', 'subsection', '2.1', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 6, 'Reparos localizados (pothole, trincas, lama) — manutenção rotina corretiva. Pothole (panela): origem afundamento localizado + desprendimento material. Reparação: escavação perímetro, limpeza, aplicação tack coat, preenchimento CBUQ. Custo SICRO 2024: R$ 200-270 por pothole (2-4 horas mão-obra, 100kg CBUQ). Vida útil reparo: 3-5 anos típico (apenas paliativo se estrutura danificada). Trinca alligator: origem fadiga estrutural. Reparação: selagem (asfalto quente + areia) precoce (<5mm abertura), fresagem + recapeamento posterior. Lama: origem umidade excessiva base, compactação inadequada. Reparação: drenagem (escavação lateral), exposição secagem (2-4 semanas), recompactação. Limpeza: varrição mecanizada + palha (folhas, detritos). Frequência DNIT: manutenção preventiva (antes falha) vs corretiva (pós-falha). Custo anual manutenção: R$ 5.000-15.000/100km (depende tráfego, condição inicial). Planejamento: contrato mantenedora com meta disponibilidade 98%+ (reparos emergenciais <2h).', CEIL(LENGTH('Reparos localizados (pothole, trincas, lama) — manutenção rotina corretiva. Pothole (panela): origem afundamento localizado + desprendimento material. Reparação: escavação perímetro, limpeza, aplicação tack coat, preenchimento CBUQ. Custo SICRO 2024: R$ 200-270 por pothole (2-4 horas mão-obra, 100kg CBUQ). Vida útil reparo: 3-5 anos típico (apenas paliativo se estrutura danificada). Trinca alligator: origem fadiga estrutural. Reparação: selagem (asfalto quente + areia) precoce (<5mm abertura), fresagem + recapeamento posterior. Lama: origem umidade excessiva base, compactação inadequada. Reparação: drenagem (escavação lateral), exposição secagem (2-4 semanas), recompactação. Limpeza: varrição mecanizada + palha (folhas, detritos). Frequência DNIT: manutenção preventiva (antes falha) vs corretiva (pós-falha). Custo anual manutenção: R$ 5.000-15.000/100km (depende tráfego, condição inicial). Planejamento: contrato mantenedora com meta disponibilidade 98%+ (reparos emergenciais <2h).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:reparos_localizados', 'categoria', 'reparos_localizados', 'section', '2', 'subsection', '2.2', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 7, 'Reabilitação drenagem — limpeza bueiros, reparação sarjetas, substituição drenos obstruídos. Problemas comuns: colmatação (sedimento, folhas) bueiro → redução vazão → alagamento; erosão sarjeta (inadequada contenção) → perda seção; ruptura dreno (raízes, carga excessiva) → perda eficácia. Limpeza bueiro: vácuo caminhão-tanque (desconecta entrada, suga sedimento), custo R$ 1.000-2.000/bueiro. Reparação sarjeta: raspagem sedimento + revestimento (gavião/concreto) se erosionada, custo R$ 30-100/m². Substituição dreno: escavação 1-2m profundidade, remoção dreno danificado, instalação novo PEAD perfurado + brita + geotêxtil, custo R$ 3.000-8.000 por 100m. Frequência: limpeza anual (preventiva), reparação conforme inspeção diagnóstico (bianual). Impacto: drenagem funcional -50% manutenção pavimento (umidade reduzida); drenagem danificada +30% deterioração (aceleração colapso). Exemplo BR-101 ES: reabilitação drenagem 50km → custo R$ 2.250-35.000/km (depende severidade). Norma DNIT 108/2009.', CEIL(LENGTH('Reabilitação drenagem — limpeza bueiros, reparação sarjetas, substituição drenos obstruídos. Problemas comuns: colmatação (sedimento, folhas) bueiro → redução vazão → alagamento; erosão sarjeta (inadequada contenção) → perda seção; ruptura dreno (raízes, carga excessiva) → perda eficácia. Limpeza bueiro: vácuo caminhão-tanque (desconecta entrada, suga sedimento), custo R$ 1.000-2.000/bueiro. Reparação sarjeta: raspagem sedimento + revestimento (gavião/concreto) se erosionada, custo R$ 30-100/m². Substituição dreno: escavação 1-2m profundidade, remoção dreno danificado, instalação novo PEAD perfurado + brita + geotêxtil, custo R$ 3.000-8.000 por 100m. Frequência: limpeza anual (preventiva), reparação conforme inspeção diagnóstico (bianual). Impacto: drenagem funcional -50% manutenção pavimento (umidade reduzida); drenagem danificada +30% deterioração (aceleração colapso). Exemplo BR-101 ES: reabilitação drenagem 50km → custo R$ 2.250-35.000/km (depende severidade). Norma DNIT 108/2009.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:reabilitacao_drenagem', 'categoria', 'reabilitacao_drenagem', 'section', '2', 'subsection', '2.3', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 8, 'Análise LCC (Ciclo de Vida 30 anos) — comparação custo total CBUQ vs CCP vs reforços. Entradas: custo inicial (construção), custo O&M (manutenção anual), custo reabilitação (reforço/recapeamento ano 12-15), valor residual, taxa desconto (6-8% típico). Exemplo CBUQ 30 anos: inicial R$ 2M (100km), manutenção R$ 100k/ano×30, reforço ano 15 R$ 800k, residual 10% → VPL ~R$ 6M (desconto 6%). Exemplo CCP: inicial R$ 2.8M (+40%), manutenção R$ 20k/ano, sem reforço, residual 20% → VPL ~R$ 2.8M (desconto 6%). Comparação: CCP melhor economicamente (VPL menor) + vida útil superior (50 anos vs 30). Sensibilidade: tráfego +20% → CBUQ reforço ano 10 (VPL +500k), CCP indiferente. Custo usuário: tempo congestionamento reabilitação, custo combustível extra desvios. Análise ampliada: VPL + custos usuário + custo ambiental (emissões CO₂) → CCP ainda vantajoso. Norma DNIT 006/2003, BNDES análise econômica.', CEIL(LENGTH('Análise LCC (Ciclo de Vida 30 anos) — comparação custo total CBUQ vs CCP vs reforços. Entradas: custo inicial (construção), custo O&M (manutenção anual), custo reabilitação (reforço/recapeamento ano 12-15), valor residual, taxa desconto (6-8% típico). Exemplo CBUQ 30 anos: inicial R$ 2M (100km), manutenção R$ 100k/ano×30, reforço ano 15 R$ 800k, residual 10% → VPL ~R$ 6M (desconto 6%). Exemplo CCP: inicial R$ 2.8M (+40%), manutenção R$ 20k/ano, sem reforço, residual 20% → VPL ~R$ 2.8M (desconto 6%). Comparação: CCP melhor economicamente (VPL menor) + vida útil superior (50 anos vs 30). Sensibilidade: tráfego +20% → CBUQ reforço ano 10 (VPL +500k), CCP indiferente. Custo usuário: tempo congestionamento reabilitação, custo combustível extra desvios. Análise ampliada: VPL + custos usuário + custo ambiental (emissões CO₂) → CCP ainda vantajoso. Norma DNIT 006/2003, BNDES análise econômica.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:analise_lcc', 'categoria', 'analise_lcc', 'section', '3', 'subsection', '3.1', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 9, 'Extensão vida útil — técnicas reforço (CBUQ), recapeamento (CBUQ), reabilitação (reconstituição). Reforço: CBUQ 3-6 cm sobreposto (compatibilidade ligante). Pré-requisito: base intacta (CBR in situ ≥3%), drenagem funcional. Benefício: extensão +8-12 anos, custo R$ 10-20M/100km. Caso BR-116 RJ reforço 2019: CBUQ 6cm → ICP 82 em 5 anos, vida +10 anos. Recapeamento: CBUQ 3-5 cm (com/sem fresagem). Pré-requisito: ICP 40-70, afundamento <20mm. Benefício: extensão +10-15 anos, custo menor reforço (R$ 8-15M/100km). Reabilitação parcial: fresagem 3-5cm + CBUQ novo (remove camada danificada). Pré-requisito: ICP 30-50. Reabilitação total: demolição pavimento, reconstituição camadas. Pré-requisito: ICP <30, estrutura falha. Decisão técnica: matriz ICP vs afundamento → opção ótima. Decisão econômica: VPL 30 anos período projeto → reforço precoce vs recapeamento tardio. Custo-benefício: reforço ano 12 (VPL menor) vs esperar ano 18 recapeamento (urgência maior, custo mais alto). Norma AASHTO M-E, DNIT Manual.', CEIL(LENGTH('Extensão vida útil — técnicas reforço (CBUQ), recapeamento (CBUQ), reabilitação (reconstituição). Reforço: CBUQ 3-6 cm sobreposto (compatibilidade ligante). Pré-requisito: base intacta (CBR in situ ≥3%), drenagem funcional. Benefício: extensão +8-12 anos, custo R$ 10-20M/100km. Caso BR-116 RJ reforço 2019: CBUQ 6cm → ICP 82 em 5 anos, vida +10 anos. Recapeamento: CBUQ 3-5 cm (com/sem fresagem). Pré-requisito: ICP 40-70, afundamento <20mm. Benefício: extensão +10-15 anos, custo menor reforço (R$ 8-15M/100km). Reabilitação parcial: fresagem 3-5cm + CBUQ novo (remove camada danificada). Pré-requisito: ICP 30-50. Reabilitação total: demolição pavimento, reconstituição camadas. Pré-requisito: ICP <30, estrutura falha. Decisão técnica: matriz ICP vs afundamento → opção ótima. Decisão econômica: VPL 30 anos período projeto → reforço precoce vs recapeamento tardio. Custo-benefício: reforço ano 12 (VPL menor) vs esperar ano 18 recapeamento (urgência maior, custo mais alto). Norma AASHTO M-E, DNIT Manual.') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:extensao_vida_util', 'categoria', 'extensao_vida_util', 'section', '3', 'subsection', '3.2', 'collection_slug', 'rodovias-om')
  UNION ALL SELECT 10, 'Tecnologias avançadas O&M — SIG (Sistemas Informação Geográfica) integração dados (lesões mapa, tráfego, drenagem), modelos preditivos (machine learning ICP vs fatores), sensor rede (piezômetro automático, acelerômetro talude, nível água drenagem). Exemplo: SIG BR-116 RJ visualiza ICP 57.6 km 127-128 + VDM crescimento 4.7% + drenagem status funcional → alerta: reforço recomendado 2025-2026 (prazo 18 meses). Sensor rede: monitoramento contínuo poropressão, temperatura asfalto (sensibilidade E* climático), tráfego real-time (crescimento não-previsto detecção automática). Custo implementação: R$ 50.000-200.000 rodovia (SIG + rede sensores 5-10 pontos). Benefício: atuação proativa (antes falha), economia manutenção emergencial (-40-50%), dados científicos retroalimentam modelos preditivos. Futuro: integração V2I (vehicle-to-infrastructure) → feedback tráfego direto, otimização rota via condição pavimento (economia combustível usuário). Legislação: esperado Brasil adotar SIG obrigatório concessões (3-5 anos), IoT sensores em norma (futuro DNIT).', CEIL(LENGTH('Tecnologias avançadas O&M — SIG (Sistemas Informação Geográfica) integração dados (lesões mapa, tráfego, drenagem), modelos preditivos (machine learning ICP vs fatores), sensor rede (piezômetro automático, acelerômetro talude, nível água drenagem). Exemplo: SIG BR-116 RJ visualiza ICP 57.6 km 127-128 + VDM crescimento 4.7% + drenagem status funcional → alerta: reforço recomendado 2025-2026 (prazo 18 meses). Sensor rede: monitoramento contínuo poropressão, temperatura asfalto (sensibilidade E* climático), tráfego real-time (crescimento não-previsto detecção automática). Custo implementação: R$ 50.000-200.000 rodovia (SIG + rede sensores 5-10 pontos). Benefício: atuação proativa (antes falha), economia manutenção emergencial (-40-50%), dados científicos retroalimentam modelos preditivos. Futuro: integração V2I (vehicle-to-infrastructure) → feedback tráfego direto, otimização rota via condição pavimento (economia combustível usuário). Legislação: esperado Brasil adotar SIG obrigatório concessões (3-5 anos), IoT sensores em norma (futuro DNIT).') / 4)::int, jsonb_build_object('prefix_storage', 'rod:om:tecnologias_avancadas', 'categoria', 'tecnologias_avancadas', 'section', '3', 'subsection', '3.3', 'collection_slug', 'rodovias-om')
) chunks;

COMMIT;

-- Verification
SELECT
  COUNT(*) as total_chunks,
  COUNT(DISTINCT metadados_chunk->>'prefix_storage') as distinct_prefixes,
  (SELECT COUNT(*) FROM manta_rag_documents WHERE doc_id = 'rod-om-especializacoes-20260804') as documents_created
FROM manta_rag_chunks
WHERE doc_id = 'rod-om-especializacoes-20260804';
