"""Test fixtures with realistic API responses."""

# GitHub fixtures
GITHUB_REPO_RESPONSE = {
    "id": 1296269,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
    "name": "Hello-World",
    "full_name": "octocat/Hello-World",
    "owner": {
        "login": "octocat",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "type": "User",
    },
    "private": False,
    "html_url": "https://github.com/octocat/Hello-World",
    "description": "This your first repo!",
    "fork": False,
    "created_at": "2011-01-26T19:01:12Z",
    "updated_at": "2011-01-26T19:14:43Z",
    "pushed_at": "2011-01-26T19:06:43Z",
    "homepage": "https://github.com",
    "size": 180,
    "stargazers_count": 80,
    "watchers_count": 80,
    "language": "Python",
    "has_issues": True,
    "has_projects": True,
    "has_downloads": True,
    "has_wiki": True,
    "has_pages": True,
    "forks_count": 9,
    "mirror_url": None,
    "open_issues_count": 0,
    "forks": 9,
    "open_issues": 0,
    "watchers": 80,
    "default_branch": "master",
    "has_discussions": True,
}

GITHUB_PR_RESPONSE = {
    "url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347",
    "id": 1,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MQ==",
    "html_url": "https://github.com/octocat/Hello-World/pull/1347",
    "diff_url": "https://github.com/octocat/Hello-World/pull/1347.diff",
    "patch_url": "https://github.com/octocat/Hello-World/pull/1347.patch",
    "issue_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
    "commits_url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits",
    "review_comments_url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments",
    "review_comment_url": "https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments",
    "statuses_url": "https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aeae053e823e8ac3db6",
    "number": 1347,
    "state": "open",
    "title": "Amazing new feature",
    "body": "Please pull these awesome changes in!",
    "created_at": "2011-01-26T19:01:12Z",
    "updated_at": "2011-01-26T19:01:12Z",
    "closed_at": None,
    "merged_at": None,
    "merge_commit_sha": "e5bd3914e2e596debea16f433f57407b4db9b3fe",
    "user": {
        "login": "octocat",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "type": "User",
    },
    "labels": [
        {
            "id": 1,
            "url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
            "name": "bug",
            "color": "f29513",
        }
    ],
    "head": {"label": "octocat:new-topic", "ref": "new-topic", "sha": "6dcb09b5b57875f334f61aeae053e823e8ac3db6"},
    "base": {"label": "octocat:master", "ref": "master", "sha": "6dcb09b5b57875f334f61aeae053e823e8ac3db6"},
    "review_comments": 0,
}

GITHUB_COMMIT_RESPONSE = {
    "sha": "6dcb09b5b57875f334f61aeae053e823e8ac3db6",
    "node_id": "MDY6Q29tbWl0NmRjYjA5YjViNTc4NzVmMzM0ZjYxYWVhZTA1M2U4MjNlOGFjM2RiNg==",
    "url": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aeae053e823e8ac3db6",
    "html_url": "https://github.com/octocat/Hello-World/commit/6dcb09b5b57875f334f61aeae053e823e8ac3db6",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aeae053e823e8ac3db6/comments",
    "author": {
        "date": "2011-04-22T13:33:48Z",
        "name": "Monalisa Octocat",
        "email": "support@github.com",
    },
    "committer": {
        "date": "2011-04-22T13:33:48Z",
        "name": "Monalisa Octocat",
        "email": "support@github.com",
    },
    "message": "Fix all the bugs",
    "tree": {
        "sha": "f9d5a07f22b679300ebe3d4a43f7a12b74b904d7",
        "url": "https://api.github.com/repos/octocat/Hello-World/git/trees/f9d5a07f22b679300ebe3d4a43f7a12b74b904d7",
    },
    "parents": [
        {
            "sha": "6dcb09b5b57875f334f61aeae053e823e8ac3db6",
            "url": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aeae053e823e8ac3db6",
            "html_url": "https://github.com/octocat/Hello-World/commit/6dcb09b5b57875f334f61aeae053e823e8ac3db6",
        }
    ],
}

# GitLab fixtures
GITLAB_PROJECT_RESPONSE = {
    "id": 4,
    "description": "My awesome project",
    "name": "Flight",
    "name_with_namespace": "Twitter / Flight",
    "path": "flight",
    "path_with_namespace": "twitter/flight",
    "created_at": "2013-09-30T13:46:02Z",
    "default_branch": "master",
    "tag_list": ["awesome", "project"],
    "ssh_url_to_repo": "git@gitlab.com:twitter/flight.git",
    "http_url_to_repo": "http://gitlab.com/twitter/flight.git",
    "web_url": "http://gitlab.com/twitter/flight",
    "avatar_url": "http://gravatar.com/avatar/c2525a7f58ae3776070e44c106c48e15?s=80&d=identicon",
    "visibility": "public",
    "issues_enabled": True,
    "merge_requests_enabled": True,
    "wiki_enabled": True,
    "jobs_enabled": True,
    "snippets_enabled": True,
    "container_registry_enabled": True,
    "created_at": "2013-09-30T13:46:02Z",
    "last_activity_at": "2013-09-30T13:46:02Z",
    "shared_runners_enabled": True,
    "creator_id": 1,
    "archived": False,
    "avatar_url": None,
    "description": "My awesome project",
    "issues_enabled": True,
    "open_issues_count": 0,
    "merge_requests_enabled": True,
    "wiki_enabled": True,
    "jobs_enabled": True,
    "snippets_enabled": False,
    "container_registry_enabled": False,
    "discussions_enabled": False,
}

# Bitbucket fixtures
BITBUCKET_REPO_RESPONSE = {
    "scm": "git",
    "website": "",
    "has_wiki": False,
    "name": "Hello-World",
    "links": {
        "watchers": {"href": "https://bitbucket.org/api/2.0/repositories/octocat/Hello-World/watchers"},
        "branches": {"href": "https://bitbucket.org/api/2.0/repositories/octocat/Hello-World/refs/branches"},
        "tags": {"href": "https://bitbucket.org/api/2.0/repositories/octocat/Hello-World/refs/tags"},
        "commits": {"href": "https://bitbucket.org/api/2.0/repositories/octocat/Hello-World/commits"},
        "clone": [
            {
                "href": "https://bitbucket.org/octocat/Hello-World",
                "name": "http",
            },
            {
                "href": "git@bitbucket.org:octocat/Hello-World.git",
                "name": "ssh",
            },
        ],
        "self": {"href": "https://bitbucket.org/api/2.0/repositories/octocat/Hello-World"},
        "source": {"href": "https://bitbucket.org/api/2.0/repositories/octocat/Hello-World/src"},
        "html": {"href": "https://bitbucket.org/octocat/Hello-World"},
        "avatar": {"href": "https://bytebucket.org/account/octocat/Hello-World/raw/master/images/theme/avatar/16/"},
    },
    "project": {
        "type": "project",
        "name": None,
        "key": "HELLO",
        "is_private": False,
        "uuid": "{uuid}",
        "links": {
            "self": {"href": "https://bitbucket.org/api/2.0/workspaces/octocat"},
            "html": {"href": "https://bitbucket.org/octocat"},
            "avatar": {
                "href": "https://bitbucket.org/account/octocat/avatar/"
            },
        },
    },
    "language": "python",
    "created_on": "2011-12-20T11:00:48.147141+00:00",
    "updated_on": "2014-06-12T03:19:17.753395+00:00",
    "size": 209710,
    "type": "repository",
    "is_private": False,
    "description": "My awesome project",
    "has_issues": False,
    "has_downloads": True,
    "uuid": "{uuid}",
    "mainbranch": {"name": "master"},
}

# Gitea fixtures
GITEA_REPO_RESPONSE = {
    "id": 1,
    "owner": {
        "id": 1,
        "username": "octocat",
        "login": "octocat",
        "full_name": "Octo Cat",
        "email": "octocat@example.com",
        "avatar_url": "https://avatars.example.com/u/1?v=4",
    },
    "name": "Hello-World",
    "full_name": "octocat/Hello-World",
    "description": "My awesome project",
    "private": False,
    "empty": False,
    "mirror": False,
    "size": 180,
    "html_url": "https://gitea.example.com/octocat/Hello-World",
    "ssh_url": "git@gitea.example.com:octocat/Hello-World.git",
    "clone_url": "https://gitea.example.com/octocat/Hello-World.git",
    "website": "https://github.com",
    "stars_count": 80,
    "forks_count": 9,
    "watchers_count": 80,
    "open_issues_count": 0,
    "open_pr_counter": 0,
    "created_at": "2011-01-26T19:01:12Z",
    "updated_at": "2011-01-26T19:14:43Z",
    "pushed_at": "2011-01-26T19:06:43Z",
    "default_branch": "master",
    "has_issues": True,
    "has_wiki": True,
    "has_discussions": False,
}
